// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type VerificationBlockedNid struct {
	NidHash   string
	Reason    string
	BlockedAt time.Time
}

type VerificationDocument struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	ItemType   string
	Kind       string
	MediaID    uuid.UUID
	Current    bool
	CreatedAt  time.Time
}

type VerificationItem struct {
	ProviderID      uuid.UUID
	ItemType        string
	Status          string
	RejectionReason string
	Fields          []byte
	SubmittedAt     *time.Time
	DecidedAt       *time.Time
	DecidedBy       *uuid.UUID
	ExpiresAt       *time.Time
}

type VerificationLevel struct {
	ProviderID     uuid.UUID
	Level          int32
	Level2PassedAt *time.Time
	Blocked        bool
	ServiceIds     []uuid.UUID
	SubmittedAt    *time.Time
	UpdatedAt      time.Time
}

type VerificationLevel2Session struct {
	ID            uuid.UUID
	ProviderID    uuid.UUID
	ServiceID     uuid.UUID
	ScheduledAt   time.Time
	Location      string
	Status        string
	Result        *string
	Checklist     []byte
	Notes         string
	VisitLat      *float64
	VisitLng      *float64
	PhotoMediaIds []uuid.UUID
	DecidedBy     *uuid.UUID
	DecidedAt     *time.Time
	CreatedAt     time.Time
}

type VerificationNidRecord struct {
	ProviderID    uuid.UUID
	NidCiphertext []byte
	NidHash       string
	UpdatedAt     time.Time
}

type VerificationOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type VerificationProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type VerificationRemindersSent struct {
	ProviderID uuid.UUID
	ItemType   string
	ExpiresAt  time.Time
	DaysBefore int32
	SentAt     time.Time
}
