// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const blockNID = `-- name: BlockNID :exec
INSERT INTO verification.blocked_nids (nid_hash, reason)
SELECT nid_hash, $1 FROM verification.nid_records WHERE provider_id = $2
ON CONFLICT DO NOTHING
`

type BlockNIDParams struct {
	Reason     string
	ProviderID uuid.UUID
}

func (q *Queries) BlockNID(ctx context.Context, arg BlockNIDParams) error {
	_, err := q.db.Exec(ctx, blockNID, arg.Reason, arg.ProviderID)
	return err
}

const countPendingReviews = `-- name: CountPendingReviews :one
SELECT count(DISTINCT l.provider_id) FROM verification.levels l
JOIN verification.items i ON i.provider_id = l.provider_id AND i.status = 'pending'
WHERE l.submitted_at IS NOT NULL
`

func (q *Queries) CountPendingReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const currentDocuments = `-- name: CurrentDocuments :many
SELECT id, item_type, kind, media_id, created_at FROM verification.documents
WHERE provider_id = $1 AND current ORDER BY created_at, id
`

type CurrentDocumentsRow struct {
	ID        uuid.UUID
	ItemType  string
	Kind      string
	MediaID   uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) CurrentDocuments(ctx context.Context, providerID uuid.UUID) ([]CurrentDocumentsRow, error) {
	rows, err := q.db.Query(ctx, currentDocuments, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurrentDocumentsRow
	for rows.Next() {
		var i CurrentDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.Kind,
			&i.MediaID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureLevel = `-- name: EnsureLevel :exec
INSERT INTO verification.levels (provider_id) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) EnsureLevel(ctx context.Context, providerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureLevel, providerID)
	return err
}

const expiredBy = `-- name: ExpiredBy :many
SELECT DISTINCT provider_id FROM verification.items WHERE status = 'approved' AND expires_at <= $1
`

func (q *Queries) ExpiredBy(ctx context.Context, expiresAt *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, expiredBy, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var provider_id uuid.UUID
		if err := rows.Scan(&provider_id); err != nil {
			return nil, err
		}
		items = append(items, provider_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expiringBetween = `-- name: ExpiringBetween :many
SELECT provider_id, item_type, expires_at::timestamptz AS expires_at FROM verification.items
WHERE status = 'approved' AND expires_at > $1 AND expires_at <= $2 ORDER BY expires_at
`

type ExpiringBetweenParams struct {
	AfterAt *time.Time
	UntilAt *time.Time
}

type ExpiringBetweenRow struct {
	ProviderID uuid.UUID
	ItemType   string
	ExpiresAt  time.Time
}

func (q *Queries) ExpiringBetween(ctx context.Context, arg ExpiringBetweenParams) ([]ExpiringBetweenRow, error) {
	rows, err := q.db.Query(ctx, expiringBetween, arg.AfterAt, arg.UntilAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpiringBetweenRow
	for rows.Next() {
		var i ExpiringBetweenRow
		if err := rows.Scan(&i.ProviderID, &i.ItemType, &i.ExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO verification.documents (id, provider_id, item_type, kind, media_id, created_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDocumentParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	ItemType   string
	Kind       string
	MediaID    uuid.UUID
	CreatedAt  time.Time
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.Exec(ctx, insertDocument,
		arg.ID,
		arg.ProviderID,
		arg.ItemType,
		arg.Kind,
		arg.MediaID,
		arg.CreatedAt,
	)
	return err
}

const itemsByProvider = `-- name: ItemsByProvider :many
SELECT item_type, status, rejection_reason, fields, submitted_at, decided_at, decided_by, expires_at
FROM verification.items WHERE provider_id = $1
`

type ItemsByProviderRow struct {
	ItemType        string
	Status          string
	RejectionReason string
	Fields          []byte
	SubmittedAt     *time.Time
	DecidedAt       *time.Time
	DecidedBy       *uuid.UUID
	ExpiresAt       *time.Time
}

func (q *Queries) ItemsByProvider(ctx context.Context, providerID uuid.UUID) ([]ItemsByProviderRow, error) {
	rows, err := q.db.Query(ctx, itemsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemsByProviderRow
	for rows.Next() {
		var i ItemsByProviderRow
		if err := rows.Scan(
			&i.ItemType,
			&i.Status,
			&i.RejectionReason,
			&i.Fields,
			&i.SubmittedAt,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const levelByProvider = `-- name: LevelByProvider :one
SELECT provider_id, level, level2_passed_at, blocked, service_ids, submitted_at
FROM verification.levels WHERE provider_id = $1
`

type LevelByProviderRow struct {
	ProviderID     uuid.UUID
	Level          int32
	Level2PassedAt *time.Time
	Blocked        bool
	ServiceIds     []uuid.UUID
	SubmittedAt    *time.Time
}

func (q *Queries) LevelByProvider(ctx context.Context, providerID uuid.UUID) (LevelByProviderRow, error) {
	row := q.db.QueryRow(ctx, levelByProvider, providerID)
	var i LevelByProviderRow
	err := row.Scan(
		&i.ProviderID,
		&i.Level,
		&i.Level2PassedAt,
		&i.Blocked,
		&i.ServiceIds,
		&i.SubmittedAt,
	)
	return i, err
}

const levels = `-- name: Levels :many
SELECT provider_id, level FROM verification.levels WHERE provider_id = ANY($1::uuid[])
`

type LevelsRow struct {
	ProviderID uuid.UUID
	Level      int32
}

func (q *Queries) Levels(ctx context.Context, ids []uuid.UUID) ([]LevelsRow, error) {
	rows, err := q.db.Query(ctx, levels, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LevelsRow
	for rows.Next() {
		var i LevelsRow
		if err := rows.Scan(&i.ProviderID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, provider_id, service_id, scheduled_at, location, status, result, checklist, notes, visit_lat, visit_lng,
    photo_media_ids, decided_by, decided_at, created_at
FROM verification.level2_sessions
WHERE ($1::uuid IS NULL OR provider_id = $1)
  AND ($2::text IS NULL OR status = $2)
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3, $4::uuid))
ORDER BY created_at DESC, id DESC LIMIT $5
`

type ListSessionsParams struct {
	ProviderID *uuid.UUID
	Status     *string
	BeforeAt   *time.Time
	BeforeID   uuid.UUID
	MaxRows    int32
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]VerificationLevel2Session, error) {
	rows, err := q.db.Query(ctx, listSessions,
		arg.ProviderID,
		arg.Status,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationLevel2Session
	for rows.Next() {
		var i VerificationLevel2Session
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ServiceID,
			&i.ScheduledAt,
			&i.Location,
			&i.Status,
			&i.Result,
			&i.Checklist,
			&i.Notes,
			&i.VisitLat,
			&i.VisitLng,
			&i.PhotoMediaIds,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLevel = `-- name: LockLevel :one
SELECT provider_id, level, level2_passed_at, blocked, service_ids, submitted_at
FROM verification.levels WHERE provider_id = $1 FOR UPDATE
`

type LockLevelRow struct {
	ProviderID     uuid.UUID
	Level          int32
	Level2PassedAt *time.Time
	Blocked        bool
	ServiceIds     []uuid.UUID
	SubmittedAt    *time.Time
}

func (q *Queries) LockLevel(ctx context.Context, providerID uuid.UUID) (LockLevelRow, error) {
	row := q.db.QueryRow(ctx, lockLevel, providerID)
	var i LockLevelRow
	err := row.Scan(
		&i.ProviderID,
		&i.Level,
		&i.Level2PassedAt,
		&i.Blocked,
		&i.ServiceIds,
		&i.SubmittedAt,
	)
	return i, err
}

const nIDBlocked = `-- name: NIDBlocked :one
SELECT EXISTS (SELECT 1 FROM verification.blocked_nids WHERE nid_hash = $1)
`

func (q *Queries) NIDBlocked(ctx context.Context, nidHash string) (bool, error) {
	row := q.db.QueryRow(ctx, nIDBlocked, nidHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const nIDByProvider = `-- name: NIDByProvider :one
SELECT nid_ciphertext, nid_hash FROM verification.nid_records WHERE provider_id = $1
`

type NIDByProviderRow struct {
	NidCiphertext []byte
	NidHash       string
}

func (q *Queries) NIDByProvider(ctx context.Context, providerID uuid.UUID) (NIDByProviderRow, error) {
	row := q.db.QueryRow(ctx, nIDByProvider, providerID)
	var i NIDByProviderRow
	err := row.Scan(&i.NidCiphertext, &i.NidHash)
	return i, err
}

const queue = `-- name: Queue :many
SELECT l.provider_id, l.submitted_at::timestamptz AS submitted_at, l.service_ids,
    array_agg(i.item_type ORDER BY i.item_type)::text[] AS pending_items
FROM verification.levels l
JOIN verification.items i ON i.provider_id = l.provider_id AND i.status = 'pending'
WHERE l.submitted_at IS NOT NULL
  AND ($1::uuid IS NULL OR $1 = ANY(l.service_ids))
  AND ($2::timestamptz IS NULL OR (l.submitted_at, l.provider_id) > ($2, $3::uuid))
GROUP BY l.provider_id, l.submitted_at, l.service_ids
HAVING $4::text IS NULL OR $4 = ANY(array_agg(i.item_type))
ORDER BY l.submitted_at, l.provider_id LIMIT $5
`

type QueueParams struct {
	ServiceID *uuid.UUID
	AfterAt   *time.Time
	AfterID   uuid.UUID
	ItemType  *string
	MaxRows   int32
}

type QueueRow struct {
	ProviderID   uuid.UUID
	SubmittedAt  time.Time
	ServiceIds   []uuid.UUID
	PendingItems []string
}

func (q *Queries) Queue(ctx context.Context, arg QueueParams) ([]QueueRow, error) {
	rows, err := q.db.Query(ctx, queue,
		arg.ServiceID,
		arg.AfterAt,
		arg.AfterID,
		arg.ItemType,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueRow
	for rows.Next() {
		var i QueueRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.SubmittedAt,
			&i.ServiceIds,
			&i.PendingItems,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordReminder = `-- name: RecordReminder :execrows
INSERT INTO verification.reminders_sent (provider_id, item_type, expires_at, days_before, sent_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type RecordReminderParams struct {
	ProviderID uuid.UUID
	ItemType   string
	ExpiresAt  time.Time
	DaysBefore int32
	SentAt     time.Time
}

func (q *Queries) RecordReminder(ctx context.Context, arg RecordReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordReminder,
		arg.ProviderID,
		arg.ItemType,
		arg.ExpiresAt,
		arg.DaysBefore,
		arg.SentAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireDocuments = `-- name: RetireDocuments :exec
UPDATE verification.documents SET current = false WHERE provider_id = $1 AND item_type = ANY($2::text[])
`

type RetireDocumentsParams struct {
	ProviderID uuid.UUID
	ItemTypes  []string
}

func (q *Queries) RetireDocuments(ctx context.Context, arg RetireDocumentsParams) error {
	_, err := q.db.Exec(ctx, retireDocuments, arg.ProviderID, arg.ItemTypes)
	return err
}

const saveLevel = `-- name: SaveLevel :exec
UPDATE verification.levels SET level = $2, level2_passed_at = $3, blocked = $4, service_ids = $5, submitted_at = $6, updated_at = $7
WHERE provider_id = $1
`

type SaveLevelParams struct {
	ProviderID     uuid.UUID
	Level          int32
	Level2PassedAt *time.Time
	Blocked        bool
	ServiceIds     []uuid.UUID
	SubmittedAt    *time.Time
	UpdatedAt      time.Time
}

func (q *Queries) SaveLevel(ctx context.Context, arg SaveLevelParams) error {
	_, err := q.db.Exec(ctx, saveLevel,
		arg.ProviderID,
		arg.Level,
		arg.Level2PassedAt,
		arg.Blocked,
		arg.ServiceIds,
		arg.SubmittedAt,
		arg.UpdatedAt,
	)
	return err
}

const sessionByID = `-- name: SessionByID :one
SELECT id, provider_id, service_id, scheduled_at, location, status, result, checklist, notes, visit_lat, visit_lng,
    photo_media_ids, decided_by, decided_at, created_at
FROM verification.level2_sessions WHERE id = $1
`

func (q *Queries) SessionByID(ctx context.Context, id uuid.UUID) (VerificationLevel2Session, error) {
	row := q.db.QueryRow(ctx, sessionByID, id)
	var i VerificationLevel2Session
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ServiceID,
		&i.ScheduledAt,
		&i.Location,
		&i.Status,
		&i.Result,
		&i.Checklist,
		&i.Notes,
		&i.VisitLat,
		&i.VisitLng,
		&i.PhotoMediaIds,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.CreatedAt,
	)
	return i, err
}

const sessionsByProvider = `-- name: SessionsByProvider :many
SELECT id, provider_id, service_id, scheduled_at, location, status, result, checklist, notes, visit_lat, visit_lng,
    photo_media_ids, decided_by, decided_at, created_at
FROM verification.level2_sessions WHERE provider_id = $1 ORDER BY created_at, id
`

func (q *Queries) SessionsByProvider(ctx context.Context, providerID uuid.UUID) ([]VerificationLevel2Session, error) {
	rows, err := q.db.Query(ctx, sessionsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VerificationLevel2Session
	for rows.Next() {
		var i VerificationLevel2Session
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ServiceID,
			&i.ScheduledAt,
			&i.Location,
			&i.Status,
			&i.Result,
			&i.Checklist,
			&i.Notes,
			&i.VisitLat,
			&i.VisitLng,
			&i.PhotoMediaIds,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItem = `-- name: UpsertItem :exec
INSERT INTO verification.items (provider_id, item_type, status, rejection_reason, fields, submitted_at, decided_at, decided_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (provider_id, item_type) DO UPDATE SET status = excluded.status, rejection_reason = excluded.rejection_reason,
    fields = excluded.fields, submitted_at = excluded.submitted_at, decided_at = excluded.decided_at,
    decided_by = excluded.decided_by, expires_at = excluded.expires_at
`

type UpsertItemParams struct {
	ProviderID      uuid.UUID
	ItemType        string
	Status          string
	RejectionReason string
	Fields          []byte
	SubmittedAt     *time.Time
	DecidedAt       *time.Time
	DecidedBy       *uuid.UUID
	ExpiresAt       *time.Time
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) error {
	_, err := q.db.Exec(ctx, upsertItem,
		arg.ProviderID,
		arg.ItemType,
		arg.Status,
		arg.RejectionReason,
		arg.Fields,
		arg.SubmittedAt,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.ExpiresAt,
	)
	return err
}

const upsertNID = `-- name: UpsertNID :exec
INSERT INTO verification.nid_records (provider_id, nid_ciphertext, nid_hash, updated_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (provider_id) DO UPDATE SET nid_ciphertext = excluded.nid_ciphertext, nid_hash = excluded.nid_hash, updated_at = excluded.updated_at
`

type UpsertNIDParams struct {
	ProviderID    uuid.UUID
	NidCiphertext []byte
	NidHash       string
	UpdatedAt     time.Time
}

func (q *Queries) UpsertNID(ctx context.Context, arg UpsertNIDParams) error {
	_, err := q.db.Exec(ctx, upsertNID,
		arg.ProviderID,
		arg.NidCiphertext,
		arg.NidHash,
		arg.UpdatedAt,
	)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO verification.level2_sessions (id, provider_id, service_id, scheduled_at, location, status, result, checklist, notes,
    visit_lat, visit_lng, photo_media_ids, decided_by, decided_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE SET status = excluded.status, result = excluded.result, checklist = excluded.checklist,
    notes = excluded.notes, visit_lat = excluded.visit_lat, visit_lng = excluded.visit_lng,
    photo_media_ids = excluded.photo_media_ids, decided_by = excluded.decided_by, decided_at = excluded.decided_at
`

type UpsertSessionParams struct {
	ID            uuid.UUID
	ProviderID    uuid.UUID
	ServiceID     uuid.UUID
	ScheduledAt   time.Time
	Location      string
	Status        string
	Result        *string
	Checklist     []byte
	Notes         string
	VisitLat      *float64
	VisitLng      *float64
	PhotoMediaIds []uuid.UUID
	DecidedBy     *uuid.UUID
	DecidedAt     *time.Time
	CreatedAt     time.Time
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.Exec(ctx, upsertSession,
		arg.ID,
		arg.ProviderID,
		arg.ServiceID,
		arg.ScheduledAt,
		arg.Location,
		arg.Status,
		arg.Result,
		arg.Checklist,
		arg.Notes,
		arg.VisitLat,
		arg.VisitLng,
		arg.PhotoMediaIds,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.CreatedAt,
	)
	return err
}
