// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type RatingAggregate struct {
	SubjectID   uuid.UUID
	SubjectRole string
	ReviewCount int32
	StarSum     int64
	Stars1      int32
	Stars2      int32
	Stars3      int32
	Stars4      int32
	Stars5      int32
}

type RatingOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type RatingProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type RatingReview struct {
	ID            uuid.UUID
	BookingID     uuid.UUID
	AuthorID      uuid.UUID
	AuthorRole    string
	AuthorName    string
	SubjectID     uuid.UUID
	Stars         int32
	Tags          []string
	Comment       string
	ServiceNameEn string
	ServiceNameBn string
	CreatedAt     time.Time
}

type RatingReviewableBooking struct {
	BookingID     uuid.UUID
	CustomerID    uuid.UUID
	ProviderID    uuid.UUID
	CustomerName  string
	ProviderName  string
	ServiceNameEn string
	ServiceNameBn string
	CompletedAt   time.Time
}
