// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addReviewable = `-- name: AddReviewable :exec
INSERT INTO rating.reviewable_bookings (booking_id, customer_id, provider_id, customer_name, provider_name, service_name_en,
    service_name_bn, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT DO NOTHING
`

type AddReviewableParams struct {
	BookingID     uuid.UUID
	CustomerID    uuid.UUID
	ProviderID    uuid.UUID
	CustomerName  string
	ProviderName  string
	ServiceNameEn string
	ServiceNameBn string
	CompletedAt   time.Time
}

func (q *Queries) AddReviewable(ctx context.Context, arg AddReviewableParams) error {
	_, err := q.db.Exec(ctx, addReviewable,
		arg.BookingID,
		arg.CustomerID,
		arg.ProviderID,
		arg.CustomerName,
		arg.ProviderName,
		arg.ServiceNameEn,
		arg.ServiceNameBn,
		arg.CompletedAt,
	)
	return err
}

const addToAggregate = `-- name: AddToAggregate :one
INSERT INTO rating.aggregates (subject_id, subject_role, review_count, star_sum, stars_1, stars_2, stars_3, stars_4, stars_5)
VALUES ($1, $2, 1, $3::int,
    ($3::int = 1)::int, ($3::int = 2)::int, ($3::int = 3)::int, ($3::int = 4)::int, ($3::int = 5)::int)
ON CONFLICT (subject_id, subject_role) DO UPDATE SET review_count = rating.aggregates.review_count + 1,
    star_sum = rating.aggregates.star_sum + excluded.star_sum, stars_1 = rating.aggregates.stars_1 + excluded.stars_1,
    stars_2 = rating.aggregates.stars_2 + excluded.stars_2, stars_3 = rating.aggregates.stars_3 + excluded.stars_3,
    stars_4 = rating.aggregates.stars_4 + excluded.stars_4, stars_5 = rating.aggregates.stars_5 + excluded.stars_5
RETURNING subject_id, review_count, star_sum, stars_1, stars_2, stars_3, stars_4, stars_5
`

type AddToAggregateParams struct {
	SubjectID   uuid.UUID
	SubjectRole string
	Stars       int32
}

type AddToAggregateRow struct {
	SubjectID   uuid.UUID
	ReviewCount int32
	StarSum     int64
	Stars1      int32
	Stars2      int32
	Stars3      int32
	Stars4      int32
	Stars5      int32
}

func (q *Queries) AddToAggregate(ctx context.Context, arg AddToAggregateParams) (AddToAggregateRow, error) {
	row := q.db.QueryRow(ctx, addToAggregate, arg.SubjectID, arg.SubjectRole, arg.Stars)
	var i AddToAggregateRow
	err := row.Scan(
		&i.SubjectID,
		&i.ReviewCount,
		&i.StarSum,
		&i.Stars1,
		&i.Stars2,
		&i.Stars3,
		&i.Stars4,
		&i.Stars5,
	)
	return i, err
}

const aggregates = `-- name: Aggregates :many
SELECT subject_id, review_count, star_sum, stars_1, stars_2, stars_3, stars_4, stars_5
FROM rating.aggregates WHERE subject_role = $1 AND subject_id = ANY($2::uuid[])
`

type AggregatesParams struct {
	SubjectRole string
	Ids         []uuid.UUID
}

type AggregatesRow struct {
	SubjectID   uuid.UUID
	ReviewCount int32
	StarSum     int64
	Stars1      int32
	Stars2      int32
	Stars3      int32
	Stars4      int32
	Stars5      int32
}

func (q *Queries) Aggregates(ctx context.Context, arg AggregatesParams) ([]AggregatesRow, error) {
	rows, err := q.db.Query(ctx, aggregates, arg.SubjectRole, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AggregatesRow
	for rows.Next() {
		var i AggregatesRow
		if err := rows.Scan(
			&i.SubjectID,
			&i.ReviewCount,
			&i.StarSum,
			&i.Stars1,
			&i.Stars2,
			&i.Stars3,
			&i.Stars4,
			&i.Stars5,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReview = `-- name: InsertReview :exec
INSERT INTO rating.reviews (id, booking_id, author_id, author_role, author_name, subject_id, stars, tags, comment,
    service_name_en, service_name_bn, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertReviewParams struct {
	ID            uuid.UUID
	BookingID     uuid.UUID
	AuthorID      uuid.UUID
	AuthorRole    string
	AuthorName    string
	SubjectID     uuid.UUID
	Stars         int32
	Tags          []string
	Comment       string
	ServiceNameEn string
	ServiceNameBn string
	CreatedAt     time.Time
}

func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) error {
	_, err := q.db.Exec(ctx, insertReview,
		arg.ID,
		arg.BookingID,
		arg.AuthorID,
		arg.AuthorRole,
		arg.AuthorName,
		arg.SubjectID,
		arg.Stars,
		arg.Tags,
		arg.Comment,
		arg.ServiceNameEn,
		arg.ServiceNameBn,
		arg.CreatedAt,
	)
	return err
}

const reviewableByID = `-- name: ReviewableByID :one
SELECT booking_id, customer_id, provider_id, customer_name, provider_name, service_name_en, service_name_bn, completed_at
FROM rating.reviewable_bookings WHERE booking_id = $1
`

func (q *Queries) ReviewableByID(ctx context.Context, bookingID uuid.UUID) (RatingReviewableBooking, error) {
	row := q.db.QueryRow(ctx, reviewableByID, bookingID)
	var i RatingReviewableBooking
	err := row.Scan(
		&i.BookingID,
		&i.CustomerID,
		&i.ProviderID,
		&i.CustomerName,
		&i.ProviderName,
		&i.ServiceNameEn,
		&i.ServiceNameBn,
		&i.CompletedAt,
	)
	return i, err
}

const reviews = `-- name: Reviews :many
SELECT id, booking_id, author_id, author_role, author_name, subject_id, stars, tags, comment, service_name_en, service_name_bn, created_at
FROM rating.reviews
WHERE subject_id = $1 AND author_role = $2
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3, $4::uuid))
ORDER BY created_at DESC, id DESC LIMIT $5
`

type ReviewsParams struct {
	SubjectID  uuid.UUID
	AuthorRole string
	BeforeAt   *time.Time
	BeforeID   uuid.UUID
	MaxRows    int32
}

func (q *Queries) Reviews(ctx context.Context, arg ReviewsParams) ([]RatingReview, error) {
	rows, err := q.db.Query(ctx, reviews,
		arg.SubjectID,
		arg.AuthorRole,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingReview
	for rows.Next() {
		var i RatingReview
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.AuthorID,
			&i.AuthorRole,
			&i.AuthorName,
			&i.SubjectID,
			&i.Stars,
			&i.Tags,
			&i.Comment,
			&i.ServiceNameEn,
			&i.ServiceNameBn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
