// Command strictstub writes a StrictUnimplemented type that satisfies the generated
// StrictServerInterface by returning ErrNotImplemented. Embedded one level below the
// module handlers, it lets the API serve the operations built so far while later
// phases fill in the rest.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
)

func main() {
	in := flag.String("in", "api.gen.go", "generated server file")
	out := flag.String("out", "strict_unimplemented.gen.go", "output file")
	flag.Parse()
	if err := run(*in, *out); err != nil {
		log.Fatal(err)
	}
}

func run(in, out string) error {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, in, nil, 0)
	if err != nil {
		return fmt.Errorf("parse %s: %w", in, err)
	}
	iface := findInterface(file, "StrictServerInterface")
	if iface == nil {
		return fmt.Errorf("StrictServerInterface not found in %s", in)
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/strictstub. DO NOT EDIT.\n\npackage api\n\nimport (\n\t\"context\"\n\t\"errors\"\n)\n\n")
	buf.WriteString("// ErrNotImplemented is returned by operations no module serves yet.\nvar ErrNotImplemented = errors.New(\"operation not implemented\")\n\n")
	buf.WriteString("// StrictUnimplemented answers every operation with ErrNotImplemented.\ntype StrictUnimplemented struct{}\n\n")
	for _, m := range iface.Methods.List {
		fn := m.Type.(*ast.FuncType)
		req := exprString(fset, fn.Params.List[1].Type)
		res := exprString(fset, fn.Results.List[0].Type)
		fmt.Fprintf(&buf, "// %s is not implemented yet.\nfunc (StrictUnimplemented) %s(context.Context, %s) (%s, error) {\n\treturn nil, ErrNotImplemented\n}\n\n", m.Names[0].Name, m.Names[0].Name, req, res)
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format output: %w", err)
	}
	return os.WriteFile(out, src, 0o600)
}

func findInterface(file *ast.File, name string) *ast.InterfaceType {
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if ok && ts.Name.Name == name {
				iface, _ := ts.Type.(*ast.InterfaceType)
				return iface
			}
		}
	}
	return nil
}

func exprString(fset *token.FileSet, e ast.Expr) string {
	var sb strings.Builder
	_ = format.Node(&sb, fset, e)
	return sb.String()
}
