// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type CustomerAddress struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Label      string
	Line1      string
	Line2      string
	Area       string
	Location   interface{}
	IsDefault  bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CustomerCustomer struct {
	ID           uuid.UUID
	Name         string
	PhotoMediaID *uuid.UUID
	Language     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CustomerOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type CustomerProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}
