// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addressByID = `-- name: AddressByID :one
SELECT id, customer_id, label, line1, line2, area, ST_Y(location::geometry)::float8 AS lat,
    ST_X(location::geometry)::float8 AS lng, is_default, created_at
FROM customer.addresses WHERE id = $1 AND customer_id = $2
`

type AddressByIDParams struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
}

type AddressByIDRow struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Label      string
	Line1      string
	Line2      string
	Area       string
	Lat        float64
	Lng        float64
	IsDefault  bool
	CreatedAt  time.Time
}

func (q *Queries) AddressByID(ctx context.Context, arg AddressByIDParams) (AddressByIDRow, error) {
	row := q.db.QueryRow(ctx, addressByID, arg.ID, arg.CustomerID)
	var i AddressByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.Area,
		&i.Lat,
		&i.Lng,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const clearDefault = `-- name: ClearDefault :exec
UPDATE customer.addresses SET is_default = false WHERE customer_id = $1 AND is_default
`

func (q *Queries) ClearDefault(ctx context.Context, customerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefault, customerID)
	return err
}

const countAddresses = `-- name: CountAddresses :one
SELECT count(*) FROM customer.addresses WHERE customer_id = $1
`

func (q *Queries) CountAddresses(ctx context.Context, customerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddresses, customerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomerBooking = `-- name: CountCustomerBooking :exec
UPDATE customer.customers SET bookings = bookings + 1 WHERE id = $1
`

func (q *Queries) CountCustomerBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, countCustomerBooking, id)
	return err
}

const customerByID = `-- name: CustomerByID :one
SELECT id, name, photo_media_id, language, updated_at FROM customer.customers WHERE id = $1
`

type CustomerByIDRow struct {
	ID           uuid.UUID
	Name         string
	PhotoMediaID *uuid.UUID
	Language     string
	UpdatedAt    time.Time
}

func (q *Queries) CustomerByID(ctx context.Context, id uuid.UUID) (CustomerByIDRow, error) {
	row := q.db.QueryRow(ctx, customerByID, id)
	var i CustomerByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PhotoMediaID,
		&i.Language,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :one
DELETE FROM customer.addresses WHERE id = $1 AND customer_id = $2 RETURNING is_default
`

type DeleteAddressParams struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) (bool, error) {
	row := q.db.QueryRow(ctx, deleteAddress, arg.ID, arg.CustomerID)
	var is_default bool
	err := row.Scan(&is_default)
	return is_default, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customer.customers WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO customer.addresses (id, customer_id, label, line1, line2, area, location, is_default, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6,
    ST_SetSRID(ST_MakePoint($7::float8, $8::float8), 4326)::geography,
    $9, $10, $10)
`

type InsertAddressParams struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Label      string
	Line1      string
	Line2      string
	Area       string
	Lng        float64
	Lat        float64
	IsDefault  bool
	CreatedAt  time.Time
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress,
		arg.ID,
		arg.CustomerID,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.Area,
		arg.Lng,
		arg.Lat,
		arg.IsDefault,
		arg.CreatedAt,
	)
	return err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, customer_id, label, line1, line2, area, ST_Y(location::geometry)::float8 AS lat,
    ST_X(location::geometry)::float8 AS lng, is_default, created_at
FROM customer.addresses WHERE customer_id = $1 ORDER BY is_default DESC, created_at DESC, id DESC
`

type ListAddressesRow struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Label      string
	Line1      string
	Line2      string
	Area       string
	Lat        float64
	Lng        float64
	IsDefault  bool
	CreatedAt  time.Time
}

func (q *Queries) ListAddresses(ctx context.Context, customerID uuid.UUID) ([]ListAddressesRow, error) {
	rows, err := q.db.Query(ctx, listAddresses, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAddressesRow
	for rows.Next() {
		var i ListAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Label,
			&i.Line1,
			&i.Line2,
			&i.Area,
			&i.Lat,
			&i.Lng,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomer = `-- name: LockCustomer :one
SELECT id FROM customer.customers WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockCustomer(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCustomer, id)
	err := row.Scan(&id)
	return id, err
}

const markDefault = `-- name: MarkDefault :execrows
UPDATE customer.addresses SET is_default = true WHERE id = $1 AND customer_id = $2
`

type MarkDefaultParams struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
}

func (q *Queries) MarkDefault(ctx context.Context, arg MarkDefaultParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDefault, arg.ID, arg.CustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteNewest = `-- name: PromoteNewest :exec
UPDATE customer.addresses SET is_default = true
WHERE id = (SELECT a.id FROM customer.addresses a WHERE a.customer_id = $1 ORDER BY a.created_at DESC, a.id DESC LIMIT 1)
`

func (q *Queries) PromoteNewest(ctx context.Context, customerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, promoteNewest, customerID)
	return err
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, name, phone, account_status, bookings, created_at FROM customer.customers
WHERE ($1::uuid IS NULL OR id = $1::uuid)
  AND ($2::text = '' OR lower(name) LIKE $2::text OR phone LIKE $2::text)
  AND ($3::text IS NULL OR account_status = $3::text)
  AND ($4::timestamptz IS NULL OR (created_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type SearchCustomersParams struct {
	ID       *uuid.UUID
	Pattern  string
	Status   *string
	BeforeAt *time.Time
	BeforeID uuid.UUID
	MaxRows  int32
}

type SearchCustomersRow struct {
	ID            uuid.UUID
	Name          string
	Phone         string
	AccountStatus string
	Bookings      int32
	CreatedAt     time.Time
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]SearchCustomersRow, error) {
	rows, err := q.db.Query(ctx, searchCustomers,
		arg.ID,
		arg.Pattern,
		arg.Status,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCustomersRow
	for rows.Next() {
		var i SearchCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.AccountStatus,
			&i.Bookings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerStatus = `-- name: SetCustomerStatus :exec
UPDATE customer.customers SET account_status = $2 WHERE id = $1
`

type SetCustomerStatusParams struct {
	ID            uuid.UUID
	AccountStatus string
}

func (q *Queries) SetCustomerStatus(ctx context.Context, arg SetCustomerStatusParams) error {
	_, err := q.db.Exec(ctx, setCustomerStatus, arg.ID, arg.AccountStatus)
	return err
}

const updateAddress = `-- name: UpdateAddress :execrows
UPDATE customer.addresses SET label = $1, line1 = $2, line2 = $3, area = $4,
    location = ST_SetSRID(ST_MakePoint($5::float8, $6::float8), 4326)::geography,
    updated_at = $7
WHERE id = $8 AND customer_id = $9
`

type UpdateAddressParams struct {
	Label      string
	Line1      string
	Line2      string
	Area       string
	Lng        float64
	Lat        float64
	UpdatedAt  time.Time
	ID         uuid.UUID
	CustomerID uuid.UUID
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAddress,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.Area,
		arg.Lng,
		arg.Lat,
		arg.UpdatedAt,
		arg.ID,
		arg.CustomerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCustomer = `-- name: UpsertCustomer :exec
INSERT INTO customer.customers (id, name, photo_media_id, language, created_at, updated_at, phone, account_status)
VALUES ($1, $2, $3, $4, $5, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET name = excluded.name, photo_media_id = excluded.photo_media_id,
    language = excluded.language, updated_at = excluded.updated_at, phone = excluded.phone,
    account_status = excluded.account_status
`

type UpsertCustomerParams struct {
	ID            uuid.UUID
	Name          string
	PhotoMediaID  *uuid.UUID
	Language      string
	CreatedAt     time.Time
	Phone         string
	AccountStatus string
}

func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) error {
	_, err := q.db.Exec(ctx, upsertCustomer,
		arg.ID,
		arg.Name,
		arg.PhotoMediaID,
		arg.Language,
		arg.CreatedAt,
		arg.Phone,
		arg.AccountStatus,
	)
	return err
}
