// Package api holds the server types generated from api/openapi.yaml. Files ending in
// .gen.go and openapi.gen.yaml are generated by ./pao gen and must not be edited.
package api

//go:generate oapi-codegen -config oapi-codegen.yaml openapi.gen.yaml
//go:generate go run ../../../../tools/strictstub -in api.gen.go -out strict_unimplemented.gen.go
