// Code generated by tools/strictstub. DO NOT EDIT.

package api

import (
	"context"
	"errors"
)

// ErrNotImplemented is returned by operations no module serves yet.
var ErrNotImplemented = errors.New("operation not implemented")

// StrictUnimplemented answers every operation with ErrNotImplemented.
type StrictUnimplemented struct{}

// ListAdminUsers is not implemented yet.
func (StrictUnimplemented) ListAdminUsers(context.Context, ListAdminUsersRequestObject) (ListAdminUsersResponseObject, error) {
	return nil, ErrNotImplemented
}

// InviteAdminUser is not implemented yet.
func (StrictUnimplemented) InviteAdminUser(context.Context, InviteAdminUserRequestObject) (InviteAdminUserResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateAdminUser is not implemented yet.
func (StrictUnimplemented) UpdateAdminUser(context.Context, UpdateAdminUserRequestObject) (UpdateAdminUserResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListAuditEntries is not implemented yet.
func (StrictUnimplemented) ListAuditEntries(context.Context, ListAuditEntriesRequestObject) (ListAuditEntriesResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListAdminBookings is not implemented yet.
func (StrictUnimplemented) ListAdminBookings(context.Context, ListAdminBookingsRequestObject) (ListAdminBookingsResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetAdminBooking is not implemented yet.
func (StrictUnimplemented) GetAdminBooking(context.Context, GetAdminBookingRequestObject) (GetAdminBookingResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetAdminCatalog is not implemented yet.
func (StrictUnimplemented) GetAdminCatalog(context.Context, GetAdminCatalogRequestObject) (GetAdminCatalogResponseObject, error) {
	return nil, ErrNotImplemented
}

// CreateCategory is not implemented yet.
func (StrictUnimplemented) CreateCategory(context.Context, CreateCategoryRequestObject) (CreateCategoryResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateCategory is not implemented yet.
func (StrictUnimplemented) UpdateCategory(context.Context, UpdateCategoryRequestObject) (UpdateCategoryResponseObject, error) {
	return nil, ErrNotImplemented
}

// CreateService is not implemented yet.
func (StrictUnimplemented) CreateService(context.Context, CreateServiceRequestObject) (CreateServiceResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateService is not implemented yet.
func (StrictUnimplemented) UpdateService(context.Context, UpdateServiceRequestObject) (UpdateServiceResponseObject, error) {
	return nil, ErrNotImplemented
}

// CreateSubService is not implemented yet.
func (StrictUnimplemented) CreateSubService(context.Context, CreateSubServiceRequestObject) (CreateSubServiceResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateSubService is not implemented yet.
func (StrictUnimplemented) UpdateSubService(context.Context, UpdateSubServiceRequestObject) (UpdateSubServiceResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListPriceHistory is not implemented yet.
func (StrictUnimplemented) ListPriceHistory(context.Context, ListPriceHistoryRequestObject) (ListPriceHistoryResponseObject, error) {
	return nil, ErrNotImplemented
}

// ChangePrice is not implemented yet.
func (StrictUnimplemented) ChangePrice(context.Context, ChangePriceRequestObject) (ChangePriceResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListComplaints is not implemented yet.
func (StrictUnimplemented) ListComplaints(context.Context, ListComplaintsRequestObject) (ListComplaintsResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetComplaint is not implemented yet.
func (StrictUnimplemented) GetComplaint(context.Context, GetComplaintRequestObject) (GetComplaintResponseObject, error) {
	return nil, ErrNotImplemented
}

// AssignComplaint is not implemented yet.
func (StrictUnimplemented) AssignComplaint(context.Context, AssignComplaintRequestObject) (AssignComplaintResponseObject, error) {
	return nil, ErrNotImplemented
}

// CommentOnComplaint is not implemented yet.
func (StrictUnimplemented) CommentOnComplaint(context.Context, CommentOnComplaintRequestObject) (CommentOnComplaintResponseObject, error) {
	return nil, ErrNotImplemented
}

// ResolveComplaint is not implemented yet.
func (StrictUnimplemented) ResolveComplaint(context.Context, ResolveComplaintRequestObject) (ResolveComplaintResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListAdminCustomers is not implemented yet.
func (StrictUnimplemented) ListAdminCustomers(context.Context, ListAdminCustomersRequestObject) (ListAdminCustomersResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetAdminCustomer is not implemented yet.
func (StrictUnimplemented) GetAdminCustomer(context.Context, GetAdminCustomerRequestObject) (GetAdminCustomerResponseObject, error) {
	return nil, ErrNotImplemented
}

// ChangeCustomerStatus is not implemented yet.
func (StrictUnimplemented) ChangeCustomerStatus(context.Context, ChangeCustomerStatusRequestObject) (ChangeCustomerStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetDashboard is not implemented yet.
func (StrictUnimplemented) GetDashboard(context.Context, GetDashboardRequestObject) (GetDashboardResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetDocumentViewUrl is not implemented yet.
func (StrictUnimplemented) GetDocumentViewUrl(context.Context, GetDocumentViewUrlRequestObject) (GetDocumentViewUrlResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListLevel2Sessions is not implemented yet.
func (StrictUnimplemented) ListLevel2Sessions(context.Context, ListLevel2SessionsRequestObject) (ListLevel2SessionsResponseObject, error) {
	return nil, ErrNotImplemented
}

// ScheduleLevel2Session is not implemented yet.
func (StrictUnimplemented) ScheduleLevel2Session(context.Context, ScheduleLevel2SessionRequestObject) (ScheduleLevel2SessionResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetLevel2Session is not implemented yet.
func (StrictUnimplemented) GetLevel2Session(context.Context, GetLevel2SessionRequestObject) (GetLevel2SessionResponseObject, error) {
	return nil, ErrNotImplemented
}

// RecordLevel2Result is not implemented yet.
func (StrictUnimplemented) RecordLevel2Result(context.Context, RecordLevel2ResultRequestObject) (RecordLevel2ResultResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListAdminProviders is not implemented yet.
func (StrictUnimplemented) ListAdminProviders(context.Context, ListAdminProvidersRequestObject) (ListAdminProvidersResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetAdminProvider is not implemented yet.
func (StrictUnimplemented) GetAdminProvider(context.Context, GetAdminProviderRequestObject) (GetAdminProviderResponseObject, error) {
	return nil, ErrNotImplemented
}

// ChangeProviderStatus is not implemented yet.
func (StrictUnimplemented) ChangeProviderStatus(context.Context, ChangeProviderStatusRequestObject) (ChangeProviderStatusResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListRoles is not implemented yet.
func (StrictUnimplemented) ListRoles(context.Context, ListRolesRequestObject) (ListRolesResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateRole is not implemented yet.
func (StrictUnimplemented) UpdateRole(context.Context, UpdateRoleRequestObject) (UpdateRoleResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListSettings is not implemented yet.
func (StrictUnimplemented) ListSettings(context.Context, ListSettingsRequestObject) (ListSettingsResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateSetting is not implemented yet.
func (StrictUnimplemented) UpdateSetting(context.Context, UpdateSettingRequestObject) (UpdateSettingResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListVerificationQueue is not implemented yet.
func (StrictUnimplemented) ListVerificationQueue(context.Context, ListVerificationQueueRequestObject) (ListVerificationQueueResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetVerificationReview is not implemented yet.
func (StrictUnimplemented) GetVerificationReview(context.Context, GetVerificationReviewRequestObject) (GetVerificationReviewResponseObject, error) {
	return nil, ErrNotImplemented
}

// ApproveVerificationItem is not implemented yet.
func (StrictUnimplemented) ApproveVerificationItem(context.Context, ApproveVerificationItemRequestObject) (ApproveVerificationItemResponseObject, error) {
	return nil, ErrNotImplemented
}

// RejectVerificationItem is not implemented yet.
func (StrictUnimplemented) RejectVerificationItem(context.Context, RejectVerificationItemRequestObject) (RejectVerificationItemResponseObject, error) {
	return nil, ErrNotImplemented
}

// AdminLogin is not implemented yet.
func (StrictUnimplemented) AdminLogin(context.Context, AdminLoginRequestObject) (AdminLoginResponseObject, error) {
	return nil, ErrNotImplemented
}

// ChangeAdminPassword is not implemented yet.
func (StrictUnimplemented) ChangeAdminPassword(context.Context, ChangeAdminPasswordRequestObject) (ChangeAdminPasswordResponseObject, error) {
	return nil, ErrNotImplemented
}

// AdminVerifyTotp is not implemented yet.
func (StrictUnimplemented) AdminVerifyTotp(context.Context, AdminVerifyTotpRequestObject) (AdminVerifyTotpResponseObject, error) {
	return nil, ErrNotImplemented
}

// Logout is not implemented yet.
func (StrictUnimplemented) Logout(context.Context, LogoutRequestObject) (LogoutResponseObject, error) {
	return nil, ErrNotImplemented
}

// RequestOtp is not implemented yet.
func (StrictUnimplemented) RequestOtp(context.Context, RequestOtpRequestObject) (RequestOtpResponseObject, error) {
	return nil, ErrNotImplemented
}

// VerifyOtp is not implemented yet.
func (StrictUnimplemented) VerifyOtp(context.Context, VerifyOtpRequestObject) (VerifyOtpResponseObject, error) {
	return nil, ErrNotImplemented
}

// RefreshToken is not implemented yet.
func (StrictUnimplemented) RefreshToken(context.Context, RefreshTokenRequestObject) (RefreshTokenResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListAddresses is not implemented yet.
func (StrictUnimplemented) ListAddresses(context.Context, ListAddressesRequestObject) (ListAddressesResponseObject, error) {
	return nil, ErrNotImplemented
}

// CreateAddress is not implemented yet.
func (StrictUnimplemented) CreateAddress(context.Context, CreateAddressRequestObject) (CreateAddressResponseObject, error) {
	return nil, ErrNotImplemented
}

// DeleteAddress is not implemented yet.
func (StrictUnimplemented) DeleteAddress(context.Context, DeleteAddressRequestObject) (DeleteAddressResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateAddress is not implemented yet.
func (StrictUnimplemented) UpdateAddress(context.Context, UpdateAddressRequestObject) (UpdateAddressResponseObject, error) {
	return nil, ErrNotImplemented
}

// SetDefaultAddress is not implemented yet.
func (StrictUnimplemented) SetDefaultAddress(context.Context, SetDefaultAddressRequestObject) (SetDefaultAddressResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListCustomerBookings is not implemented yet.
func (StrictUnimplemented) ListCustomerBookings(context.Context, ListCustomerBookingsRequestObject) (ListCustomerBookingsResponseObject, error) {
	return nil, ErrNotImplemented
}

// CreateBooking is not implemented yet.
func (StrictUnimplemented) CreateBooking(context.Context, CreateBookingRequestObject) (CreateBookingResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetCustomerBooking is not implemented yet.
func (StrictUnimplemented) GetCustomerBooking(context.Context, GetCustomerBookingRequestObject) (GetCustomerBookingResponseObject, error) {
	return nil, ErrNotImplemented
}

// CancelCustomerBooking is not implemented yet.
func (StrictUnimplemented) CancelCustomerBooking(context.Context, CancelCustomerBookingRequestObject) (CancelCustomerBookingResponseObject, error) {
	return nil, ErrNotImplemented
}

// DecideExtras is not implemented yet.
func (StrictUnimplemented) DecideExtras(context.Context, DecideExtrasRequestObject) (DecideExtrasResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetCustomerReceipt is not implemented yet.
func (StrictUnimplemented) GetCustomerReceipt(context.Context, GetCustomerReceiptRequestObject) (GetCustomerReceiptResponseObject, error) {
	return nil, ErrNotImplemented
}

// ReportCustomerProblem is not implemented yet.
func (StrictUnimplemented) ReportCustomerProblem(context.Context, ReportCustomerProblemRequestObject) (ReportCustomerProblemResponseObject, error) {
	return nil, ErrNotImplemented
}

// ReviewProvider is not implemented yet.
func (StrictUnimplemented) ReviewProvider(context.Context, ReviewProviderRequestObject) (ReviewProviderResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetStartCode is not implemented yet.
func (StrictUnimplemented) GetStartCode(context.Context, GetStartCodeRequestObject) (GetStartCodeResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetCatalog is not implemented yet.
func (StrictUnimplemented) GetCatalog(context.Context, GetCatalogRequestObject) (GetCatalogResponseObject, error) {
	return nil, ErrNotImplemented
}

// SearchCatalog is not implemented yet.
func (StrictUnimplemented) SearchCatalog(context.Context, SearchCatalogRequestObject) (SearchCatalogResponseObject, error) {
	return nil, ErrNotImplemented
}

// RegisterCustomerDeviceToken is not implemented yet.
func (StrictUnimplemented) RegisterCustomerDeviceToken(context.Context, RegisterCustomerDeviceTokenRequestObject) (RegisterCustomerDeviceTokenResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListCustomerNotifications is not implemented yet.
func (StrictUnimplemented) ListCustomerNotifications(context.Context, ListCustomerNotificationsRequestObject) (ListCustomerNotificationsResponseObject, error) {
	return nil, ErrNotImplemented
}

// MarkAllCustomerNotificationsRead is not implemented yet.
func (StrictUnimplemented) MarkAllCustomerNotificationsRead(context.Context, MarkAllCustomerNotificationsReadRequestObject) (MarkAllCustomerNotificationsReadResponseObject, error) {
	return nil, ErrNotImplemented
}

// MarkCustomerNotificationRead is not implemented yet.
func (StrictUnimplemented) MarkCustomerNotificationRead(context.Context, MarkCustomerNotificationReadRequestObject) (MarkCustomerNotificationReadResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetCustomerProfile is not implemented yet.
func (StrictUnimplemented) GetCustomerProfile(context.Context, GetCustomerProfileRequestObject) (GetCustomerProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateCustomerProfile is not implemented yet.
func (StrictUnimplemented) UpdateCustomerProfile(context.Context, UpdateCustomerProfileRequestObject) (UpdateCustomerProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

// FindNearbyProviders is not implemented yet.
func (StrictUnimplemented) FindNearbyProviders(context.Context, FindNearbyProvidersRequestObject) (FindNearbyProvidersResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetProviderPublicProfile is not implemented yet.
func (StrictUnimplemented) GetProviderPublicProfile(context.Context, GetProviderPublicProfileRequestObject) (GetProviderPublicProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListProviderReviews is not implemented yet.
func (StrictUnimplemented) ListProviderReviews(context.Context, ListProviderReviewsRequestObject) (ListProviderReviewsResponseObject, error) {
	return nil, ErrNotImplemented
}

// CheckServiceArea is not implemented yet.
func (StrictUnimplemented) CheckServiceArea(context.Context, CheckServiceAreaRequestObject) (CheckServiceAreaResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetService is not implemented yet.
func (StrictUnimplemented) GetService(context.Context, GetServiceRequestObject) (GetServiceResponseObject, error) {
	return nil, ErrNotImplemented
}

// CreateCustomerUpload is not implemented yet.
func (StrictUnimplemented) CreateCustomerUpload(context.Context, CreateCustomerUploadRequestObject) (CreateCustomerUploadResponseObject, error) {
	return nil, ErrNotImplemented
}

// ConfirmCustomerUpload is not implemented yet.
func (StrictUnimplemented) ConfirmCustomerUpload(context.Context, ConfirmCustomerUploadRequestObject) (ConfirmCustomerUploadResponseObject, error) {
	return nil, ErrNotImplemented
}

// DeleteMe is not implemented yet.
func (StrictUnimplemented) DeleteMe(context.Context, DeleteMeRequestObject) (DeleteMeResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetMe is not implemented yet.
func (StrictUnimplemented) GetMe(context.Context, GetMeRequestObject) (GetMeResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetMyPermissions is not implemented yet.
func (StrictUnimplemented) GetMyPermissions(context.Context, GetMyPermissionsRequestObject) (GetMyPermissionsResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetProviderCatalog is not implemented yet.
func (StrictUnimplemented) GetProviderCatalog(context.Context, GetProviderCatalogRequestObject) (GetProviderCatalogResponseObject, error) {
	return nil, ErrNotImplemented
}

// RegisterProviderDeviceToken is not implemented yet.
func (StrictUnimplemented) RegisterProviderDeviceToken(context.Context, RegisterProviderDeviceTokenRequestObject) (RegisterProviderDeviceTokenResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListEarningsJobs is not implemented yet.
func (StrictUnimplemented) ListEarningsJobs(context.Context, ListEarningsJobsRequestObject) (ListEarningsJobsResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetEarningsSummary is not implemented yet.
func (StrictUnimplemented) GetEarningsSummary(context.Context, GetEarningsSummaryRequestObject) (GetEarningsSummaryResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetEnrolment is not implemented yet.
func (StrictUnimplemented) GetEnrolment(context.Context, GetEnrolmentRequestObject) (GetEnrolmentResponseObject, error) {
	return nil, ErrNotImplemented
}

// SaveAreaStep is not implemented yet.
func (StrictUnimplemented) SaveAreaStep(context.Context, SaveAreaStepRequestObject) (SaveAreaStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SaveCodeOfConductStep is not implemented yet.
func (StrictUnimplemented) SaveCodeOfConductStep(context.Context, SaveCodeOfConductStepRequestObject) (SaveCodeOfConductStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SaveEmergencyContactStep is not implemented yet.
func (StrictUnimplemented) SaveEmergencyContactStep(context.Context, SaveEmergencyContactStepRequestObject) (SaveEmergencyContactStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// VerifyEmergencyContact is not implemented yet.
func (StrictUnimplemented) VerifyEmergencyContact(context.Context, VerifyEmergencyContactRequestObject) (VerifyEmergencyContactResponseObject, error) {
	return nil, ErrNotImplemented
}

// SaveNidStep is not implemented yet.
func (StrictUnimplemented) SaveNidStep(context.Context, SaveNidStepRequestObject) (SaveNidStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SavePersonalStep is not implemented yet.
func (StrictUnimplemented) SavePersonalStep(context.Context, SavePersonalStepRequestObject) (SavePersonalStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SavePoliceClearanceStep is not implemented yet.
func (StrictUnimplemented) SavePoliceClearanceStep(context.Context, SavePoliceClearanceStepRequestObject) (SavePoliceClearanceStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SaveSelfieStep is not implemented yet.
func (StrictUnimplemented) SaveSelfieStep(context.Context, SaveSelfieStepRequestObject) (SaveSelfieStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SaveServicesStep is not implemented yet.
func (StrictUnimplemented) SaveServicesStep(context.Context, SaveServicesStepRequestObject) (SaveServicesStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SaveSkillProofStep is not implemented yet.
func (StrictUnimplemented) SaveSkillProofStep(context.Context, SaveSkillProofStepRequestObject) (SaveSkillProofStepResponseObject, error) {
	return nil, ErrNotImplemented
}

// SubmitEnrolment is not implemented yet.
func (StrictUnimplemented) SubmitEnrolment(context.Context, SubmitEnrolmentRequestObject) (SubmitEnrolmentResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListProviderJobs is not implemented yet.
func (StrictUnimplemented) ListProviderJobs(context.Context, ListProviderJobsRequestObject) (ListProviderJobsResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetProviderJob is not implemented yet.
func (StrictUnimplemented) GetProviderJob(context.Context, GetProviderJobRequestObject) (GetProviderJobResponseObject, error) {
	return nil, ErrNotImplemented
}

// AcceptRequest is not implemented yet.
func (StrictUnimplemented) AcceptRequest(context.Context, AcceptRequestRequestObject) (AcceptRequestResponseObject, error) {
	return nil, ErrNotImplemented
}

// MarkArrived is not implemented yet.
func (StrictUnimplemented) MarkArrived(context.Context, MarkArrivedRequestObject) (MarkArrivedResponseObject, error) {
	return nil, ErrNotImplemented
}

// CancelProviderJob is not implemented yet.
func (StrictUnimplemented) CancelProviderJob(context.Context, CancelProviderJobRequestObject) (CancelProviderJobResponseObject, error) {
	return nil, ErrNotImplemented
}

// CompleteJob is not implemented yet.
func (StrictUnimplemented) CompleteJob(context.Context, CompleteJobRequestObject) (CompleteJobResponseObject, error) {
	return nil, ErrNotImplemented
}

// ProposeExtras is not implemented yet.
func (StrictUnimplemented) ProposeExtras(context.Context, ProposeExtrasRequestObject) (ProposeExtrasResponseObject, error) {
	return nil, ErrNotImplemented
}

// MarkOnTheWay is not implemented yet.
func (StrictUnimplemented) MarkOnTheWay(context.Context, MarkOnTheWayRequestObject) (MarkOnTheWayResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetProviderReceipt is not implemented yet.
func (StrictUnimplemented) GetProviderReceipt(context.Context, GetProviderReceiptRequestObject) (GetProviderReceiptResponseObject, error) {
	return nil, ErrNotImplemented
}

// RejectRequest is not implemented yet.
func (StrictUnimplemented) RejectRequest(context.Context, RejectRequestRequestObject) (RejectRequestResponseObject, error) {
	return nil, ErrNotImplemented
}

// ReportProviderProblem is not implemented yet.
func (StrictUnimplemented) ReportProviderProblem(context.Context, ReportProviderProblemRequestObject) (ReportProviderProblemResponseObject, error) {
	return nil, ErrNotImplemented
}

// ReviewCustomer is not implemented yet.
func (StrictUnimplemented) ReviewCustomer(context.Context, ReviewCustomerRequestObject) (ReviewCustomerResponseObject, error) {
	return nil, ErrNotImplemented
}

// StartJob is not implemented yet.
func (StrictUnimplemented) StartJob(context.Context, StartJobRequestObject) (StartJobResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListProviderNotifications is not implemented yet.
func (StrictUnimplemented) ListProviderNotifications(context.Context, ListProviderNotificationsRequestObject) (ListProviderNotificationsResponseObject, error) {
	return nil, ErrNotImplemented
}

// MarkAllProviderNotificationsRead is not implemented yet.
func (StrictUnimplemented) MarkAllProviderNotificationsRead(context.Context, MarkAllProviderNotificationsReadRequestObject) (MarkAllProviderNotificationsReadResponseObject, error) {
	return nil, ErrNotImplemented
}

// MarkProviderNotificationRead is not implemented yet.
func (StrictUnimplemented) MarkProviderNotificationRead(context.Context, MarkProviderNotificationReadRequestObject) (MarkProviderNotificationReadResponseObject, error) {
	return nil, ErrNotImplemented
}

// SendHeartbeat is not implemented yet.
func (StrictUnimplemented) SendHeartbeat(context.Context, SendHeartbeatRequestObject) (SendHeartbeatResponseObject, error) {
	return nil, ErrNotImplemented
}

// GoOffline is not implemented yet.
func (StrictUnimplemented) GoOffline(context.Context, GoOfflineRequestObject) (GoOfflineResponseObject, error) {
	return nil, ErrNotImplemented
}

// GoOnline is not implemented yet.
func (StrictUnimplemented) GoOnline(context.Context, GoOnlineRequestObject) (GoOnlineResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetProviderProfile is not implemented yet.
func (StrictUnimplemented) GetProviderProfile(context.Context, GetProviderProfileRequestObject) (GetProviderProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

// UpdateProviderProfile is not implemented yet.
func (StrictUnimplemented) UpdateProviderProfile(context.Context, UpdateProviderProfileRequestObject) (UpdateProviderProfileResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetMyRating is not implemented yet.
func (StrictUnimplemented) GetMyRating(context.Context, GetMyRatingRequestObject) (GetMyRatingResponseObject, error) {
	return nil, ErrNotImplemented
}

// ListMyReviews is not implemented yet.
func (StrictUnimplemented) ListMyReviews(context.Context, ListMyReviewsRequestObject) (ListMyReviewsResponseObject, error) {
	return nil, ErrNotImplemented
}

// CreateProviderUpload is not implemented yet.
func (StrictUnimplemented) CreateProviderUpload(context.Context, CreateProviderUploadRequestObject) (CreateProviderUploadResponseObject, error) {
	return nil, ErrNotImplemented
}

// ConfirmProviderUpload is not implemented yet.
func (StrictUnimplemented) ConfirmProviderUpload(context.Context, ConfirmProviderUploadRequestObject) (ConfirmProviderUploadResponseObject, error) {
	return nil, ErrNotImplemented
}

// GetVerificationStatus is not implemented yet.
func (StrictUnimplemented) GetVerificationStatus(context.Context, GetVerificationStatusRequestObject) (GetVerificationStatusResponseObject, error) {
	return nil, ErrNotImplemented
}
