// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type AdminComplaint struct {
	ID            uuid.UUID
	TicketNumber  int64
	BookingID     uuid.UUID
	ReporterID    uuid.UUID
	ReporterRole  string
	AgainstID     uuid.UUID
	Reason        string
	Description   string
	PhotoMediaIds []uuid.UUID
	Status        string
	AssigneeID    *uuid.UUID
	Resolution    string
	Verified      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ResolvedAt    *time.Time
}

type AdminComplaintComment struct {
	ID          uuid.UUID
	ComplaintID uuid.UUID
	AuthorID    uuid.UUID
	Body        string
	At          time.Time
}

type AdminOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type AdminProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type AdminSetting struct {
	Key         string
	Value       string
	Type        string
	Description string
	UpdatedAt   time.Time
	UpdatedBy   *uuid.UUID
}

type AdminStatsBookingsDaily struct {
	Day       time.Time
	Requested int32
	Completed int32
}

type AdminStatsProvider struct {
	ProviderID uuid.UUID
	Status     string
	Level      int32
}
