// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addStatsProvider = `-- name: AddStatsProvider :exec
INSERT INTO admin.stats_providers (provider_id, status, level) VALUES ($1, 'active', 0) ON CONFLICT DO NOTHING
`

func (q *Queries) AddStatsProvider(ctx context.Context, providerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, addStatsProvider, providerID)
	return err
}

const bookingsSince = `-- name: BookingsSince :many
SELECT day, requested, completed FROM admin.stats_bookings_daily WHERE day >= $1 ORDER BY day
`

func (q *Queries) BookingsSince(ctx context.Context, day time.Time) ([]AdminStatsBookingsDaily, error) {
	rows, err := q.db.Query(ctx, bookingsSince, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminStatsBookingsDaily
	for rows.Next() {
		var i AdminStatsBookingsDaily
		if err := rows.Scan(&i.Day, &i.Requested, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bumpBookings = `-- name: BumpBookings :exec
INSERT INTO admin.stats_bookings_daily (day, requested, completed) VALUES ($1, $2, $3)
ON CONFLICT (day) DO UPDATE SET requested = admin.stats_bookings_daily.requested + EXCLUDED.requested,
    completed = admin.stats_bookings_daily.completed + EXCLUDED.completed
`

type BumpBookingsParams struct {
	Day       time.Time
	Requested int32
	Completed int32
}

func (q *Queries) BumpBookings(ctx context.Context, arg BumpBookingsParams) error {
	_, err := q.db.Exec(ctx, bumpBookings, arg.Day, arg.Requested, arg.Completed)
	return err
}

const complaintByID = `-- name: ComplaintByID :one
SELECT id, ticket_number, booking_id, reporter_id, reporter_role, against_id, reason, description, photo_media_ids, status, assignee_id, resolution, verified, created_at, updated_at, resolved_at FROM admin.complaints WHERE id = $1
`

func (q *Queries) ComplaintByID(ctx context.Context, id uuid.UUID) (AdminComplaint, error) {
	row := q.db.QueryRow(ctx, complaintByID, id)
	var i AdminComplaint
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.BookingID,
		&i.ReporterID,
		&i.ReporterRole,
		&i.AgainstID,
		&i.Reason,
		&i.Description,
		&i.PhotoMediaIds,
		&i.Status,
		&i.AssigneeID,
		&i.Resolution,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const complaintsInvolving = `-- name: ComplaintsInvolving :many
SELECT id, ticket_number, booking_id, reporter_id, reporter_role, against_id, reason, description, photo_media_ids, status, assignee_id, resolution, verified, created_at, updated_at, resolved_at FROM admin.complaints WHERE reporter_id = $1 OR against_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ComplaintsInvolvingParams struct {
	ReporterID uuid.UUID
	Limit      int32
}

func (q *Queries) ComplaintsInvolving(ctx context.Context, arg ComplaintsInvolvingParams) ([]AdminComplaint, error) {
	rows, err := q.db.Query(ctx, complaintsInvolving, arg.ReporterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminComplaint
	for rows.Next() {
		var i AdminComplaint
		if err := rows.Scan(
			&i.ID,
			&i.TicketNumber,
			&i.BookingID,
			&i.ReporterID,
			&i.ReporterRole,
			&i.AgainstID,
			&i.Reason,
			&i.Description,
			&i.PhotoMediaIds,
			&i.Status,
			&i.AssigneeID,
			&i.Resolution,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countComplaintsAgainst = `-- name: CountComplaintsAgainst :one
SELECT count(*) FROM admin.complaints WHERE against_id = $1
`

func (q *Queries) CountComplaintsAgainst(ctx context.Context, againstID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countComplaintsAgainst, againstID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenComplaints = `-- name: CountOpenComplaints :one
SELECT count(*) FROM admin.complaints WHERE status <> 'resolved'
`

func (q *Queries) CountOpenComplaints(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenComplaints)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVerifiedComplaints = `-- name: CountVerifiedComplaints :one
SELECT count(*) FROM admin.complaints WHERE against_id = $1 AND verified
`

func (q *Queries) CountVerifiedComplaints(ctx context.Context, againstID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedComplaints, againstID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStatsProvider = `-- name: DeleteStatsProvider :exec
DELETE FROM admin.stats_providers WHERE provider_id = $1
`

func (q *Queries) DeleteStatsProvider(ctx context.Context, providerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStatsProvider, providerID)
	return err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO admin.complaint_comments (id, complaint_id, author_id, body, at) VALUES ($1, $2, $3, $4, $5)
`

type InsertCommentParams struct {
	ID          uuid.UUID
	ComplaintID uuid.UUID
	AuthorID    uuid.UUID
	Body        string
	At          time.Time
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment,
		arg.ID,
		arg.ComplaintID,
		arg.AuthorID,
		arg.Body,
		arg.At,
	)
	return err
}

const insertComplaint = `-- name: InsertComplaint :one
INSERT INTO admin.complaints (id, booking_id, reporter_id, reporter_role, against_id, reason, description, photo_media_ids, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING ticket_number
`

type InsertComplaintParams struct {
	ID            uuid.UUID
	BookingID     uuid.UUID
	ReporterID    uuid.UUID
	ReporterRole  string
	AgainstID     uuid.UUID
	Reason        string
	Description   string
	PhotoMediaIds []uuid.UUID
	CreatedAt     time.Time
}

func (q *Queries) InsertComplaint(ctx context.Context, arg InsertComplaintParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertComplaint,
		arg.ID,
		arg.BookingID,
		arg.ReporterID,
		arg.ReporterRole,
		arg.AgainstID,
		arg.Reason,
		arg.Description,
		arg.PhotoMediaIds,
		arg.CreatedAt,
	)
	var ticket_number int64
	err := row.Scan(&ticket_number)
	return ticket_number, err
}

const listComments = `-- name: ListComments :many
SELECT id, complaint_id, author_id, body, at FROM admin.complaint_comments WHERE complaint_id = $1 ORDER BY at, id
`

func (q *Queries) ListComments(ctx context.Context, complaintID uuid.UUID) ([]AdminComplaintComment, error) {
	rows, err := q.db.Query(ctx, listComments, complaintID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminComplaintComment
	for rows.Next() {
		var i AdminComplaintComment
		if err := rows.Scan(
			&i.ID,
			&i.ComplaintID,
			&i.AuthorID,
			&i.Body,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComplaints = `-- name: ListComplaints :many
SELECT id, ticket_number, booking_id, reporter_id, reporter_role, against_id, reason, description, photo_media_ids, status, assignee_id, resolution, verified, created_at, updated_at, resolved_at FROM admin.complaints
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::uuid IS NULL OR assignee_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListComplaintsParams struct {
	Status     *string
	AssigneeID *uuid.UUID
	BeforeAt   *time.Time
	BeforeID   uuid.UUID
	MaxRows    int32
}

func (q *Queries) ListComplaints(ctx context.Context, arg ListComplaintsParams) ([]AdminComplaint, error) {
	rows, err := q.db.Query(ctx, listComplaints,
		arg.Status,
		arg.AssigneeID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminComplaint
	for rows.Next() {
		var i AdminComplaint
		if err := rows.Scan(
			&i.ID,
			&i.TicketNumber,
			&i.BookingID,
			&i.ReporterID,
			&i.ReporterRole,
			&i.AgainstID,
			&i.Reason,
			&i.Description,
			&i.PhotoMediaIds,
			&i.Status,
			&i.AssigneeID,
			&i.Resolution,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, type, description, updated_at, updated_by FROM admin.settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]AdminSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSetting
	for rows.Next() {
		var i AdminSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Type,
			&i.Description,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockComplaint = `-- name: LockComplaint :one
SELECT id, ticket_number, booking_id, reporter_id, reporter_role, against_id, reason, description, photo_media_ids, status, assignee_id, resolution, verified, created_at, updated_at, resolved_at FROM admin.complaints WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockComplaint(ctx context.Context, id uuid.UUID) (AdminComplaint, error) {
	row := q.db.QueryRow(ctx, lockComplaint, id)
	var i AdminComplaint
	err := row.Scan(
		&i.ID,
		&i.TicketNumber,
		&i.BookingID,
		&i.ReporterID,
		&i.ReporterRole,
		&i.AgainstID,
		&i.Reason,
		&i.Description,
		&i.PhotoMediaIds,
		&i.Status,
		&i.AssigneeID,
		&i.Resolution,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const providersByLevel = `-- name: ProvidersByLevel :many
SELECT level, count(*) AS n FROM admin.stats_providers GROUP BY level
`

type ProvidersByLevelRow struct {
	Level int32
	N     int64
}

func (q *Queries) ProvidersByLevel(ctx context.Context) ([]ProvidersByLevelRow, error) {
	rows, err := q.db.Query(ctx, providersByLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProvidersByLevelRow
	for rows.Next() {
		var i ProvidersByLevelRow
		if err := rows.Scan(&i.Level, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providersByStatus = `-- name: ProvidersByStatus :many
SELECT (CASE WHEN status = 'active' AND level = 0 THEN 'pending' ELSE status END)::text AS status, count(*) AS n
FROM admin.stats_providers GROUP BY 1
`

type ProvidersByStatusRow struct {
	Status string
	N      int64
}

// An active provider without Level 1 is still pending verification (PRD §6.4).
func (q *Queries) ProvidersByStatus(ctx context.Context) ([]ProvidersByStatusRow, error) {
	rows, err := q.db.Query(ctx, providersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProvidersByStatusRow
	for rows.Next() {
		var i ProvidersByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStatsLevel = `-- name: SetStatsLevel :exec
INSERT INTO admin.stats_providers (provider_id, status, level) VALUES ($1, 'active', $2)
ON CONFLICT (provider_id) DO UPDATE SET level = EXCLUDED.level
`

type SetStatsLevelParams struct {
	ProviderID uuid.UUID
	Level      int32
}

func (q *Queries) SetStatsLevel(ctx context.Context, arg SetStatsLevelParams) error {
	_, err := q.db.Exec(ctx, setStatsLevel, arg.ProviderID, arg.Level)
	return err
}

const setStatsStatus = `-- name: SetStatsStatus :exec
INSERT INTO admin.stats_providers (provider_id, status, level) VALUES ($1, $2, 0)
ON CONFLICT (provider_id) DO UPDATE SET status = EXCLUDED.status
`

type SetStatsStatusParams struct {
	ProviderID uuid.UUID
	Status     string
}

func (q *Queries) SetStatsStatus(ctx context.Context, arg SetStatsStatusParams) error {
	_, err := q.db.Exec(ctx, setStatsStatus, arg.ProviderID, arg.Status)
	return err
}

const settingByKey = `-- name: SettingByKey :one
SELECT key, value, type, description, updated_at, updated_by FROM admin.settings WHERE key = $1
`

func (q *Queries) SettingByKey(ctx context.Context, key string) (AdminSetting, error) {
	row := q.db.QueryRow(ctx, settingByKey, key)
	var i AdminSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Type,
		&i.Description,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateComplaint = `-- name: UpdateComplaint :exec
UPDATE admin.complaints
SET status = $2, assignee_id = $3, resolution = $4, verified = $5, updated_at = $6, resolved_at = $7
WHERE id = $1
`

type UpdateComplaintParams struct {
	ID         uuid.UUID
	Status     string
	AssigneeID *uuid.UUID
	Resolution string
	Verified   bool
	UpdatedAt  time.Time
	ResolvedAt *time.Time
}

func (q *Queries) UpdateComplaint(ctx context.Context, arg UpdateComplaintParams) error {
	_, err := q.db.Exec(ctx, updateComplaint,
		arg.ID,
		arg.Status,
		arg.AssigneeID,
		arg.Resolution,
		arg.Verified,
		arg.UpdatedAt,
		arg.ResolvedAt,
	)
	return err
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE admin.settings SET value = $2, updated_at = $3, updated_by = $4 WHERE key = $1
`

type UpdateSettingParams struct {
	Key       string
	Value     string
	UpdatedAt time.Time
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.Exec(ctx, updateSetting,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}
