// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countVerifiedComplaints = `-- name: CountVerifiedComplaints :one
SELECT count(*) FROM admin.complaints WHERE against_id = $1 AND verified
`

func (q *Queries) CountVerifiedComplaints(ctx context.Context, againstID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVerifiedComplaints, againstID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, type, description, updated_at, updated_by FROM admin.settings ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]AdminSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSetting
	for rows.Next() {
		var i AdminSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Type,
			&i.Description,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settingByKey = `-- name: SettingByKey :one
SELECT key, value, type, description, updated_at, updated_by FROM admin.settings WHERE key = $1
`

func (q *Queries) SettingByKey(ctx context.Context, key string) (AdminSetting, error) {
	row := q.db.QueryRow(ctx, settingByKey, key)
	var i AdminSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Type,
		&i.Description,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateSetting = `-- name: UpdateSetting :exec
UPDATE admin.settings SET value = $2, updated_at = $3, updated_by = $4 WHERE key = $1
`

type UpdateSettingParams struct {
	Key       string
	Value     string
	UpdatedAt time.Time
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpdateSetting(ctx context.Context, arg UpdateSettingParams) error {
	_, err := q.db.Exec(ctx, updateSetting,
		arg.Key,
		arg.Value,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}
