// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type CatalogCatalogVersion struct {
	Singleton bool
	Version   int64
}

type CatalogCategory struct {
	ID        uuid.UUID
	NameEn    string
	NameBn    string
	IconKey   string
	SortOrder int32
	Published bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CatalogOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type CatalogPriceVersion struct {
	ID            uuid.UUID
	SubServiceID  uuid.UUID
	AmountPaisa   int64
	EffectiveFrom time.Time
	CreatedBy     uuid.UUID
}

type CatalogProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type CatalogService struct {
	ID                 uuid.UUID
	CategoryID         uuid.UUID
	NameEn             string
	NameBn             string
	IconKey            string
	ServiceModel       string
	RequiredLevel      int32
	SearchRadiusM      int32
	WomenProvidersOnly bool
	RequiresLevel2     bool
	Level2Checklist    []byte
	SortOrder          int32
	Published          bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type CatalogSubService struct {
	ID                    uuid.UUID
	ServiceID             uuid.UUID
	NameEn                string
	NameBn                string
	Description           []byte
	Inclusions            []byte
	Exclusions            []byte
	Unit                  string
	MaxQuantity           int32
	SortOrder             int32
	Published             bool
	CurrentPriceVersionID *uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	SearchText            *string
}
