// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPrice = `-- name: AddPrice :exec
WITH p AS (
    INSERT INTO catalog.price_versions (id, sub_service_id, amount_paisa, effective_from, created_by)
    VALUES ($1, $2, $3, $4, $5) RETURNING id, sub_service_id
)
UPDATE catalog.sub_services s SET current_price_version_id = p.id FROM p WHERE s.id = p.sub_service_id
`

type AddPriceParams struct {
	ID            uuid.UUID
	SubServiceID  uuid.UUID
	AmountPaisa   int64
	EffectiveFrom time.Time
	CreatedBy     uuid.UUID
}

func (q *Queries) AddPrice(ctx context.Context, arg AddPriceParams) error {
	_, err := q.db.Exec(ctx, addPrice,
		arg.ID,
		arg.SubServiceID,
		arg.AmountPaisa,
		arg.EffectiveFrom,
		arg.CreatedBy,
	)
	return err
}

const bumpVersion = `-- name: BumpVersion :one
UPDATE catalog.catalog_version SET version = version + 1 RETURNING version
`

func (q *Queries) BumpVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, bumpVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const categories = `-- name: Categories :many
SELECT id, name_en, name_bn, icon_key, sort_order, published FROM catalog.categories ORDER BY sort_order, name_en
`

type CategoriesRow struct {
	ID        uuid.UUID
	NameEn    string
	NameBn    string
	IconKey   string
	SortOrder int32
	Published bool
}

func (q *Queries) Categories(ctx context.Context) ([]CategoriesRow, error) {
	rows, err := q.db.Query(ctx, categories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriesRow
	for rows.Next() {
		var i CategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.NameEn,
			&i.NameBn,
			&i.IconKey,
			&i.SortOrder,
			&i.Published,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS (SELECT 1 FROM catalog.categories WHERE id = $1)
`

func (q *Queries) CategoryExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const priceHistory = `-- name: PriceHistory :many
SELECT id, sub_service_id, amount_paisa, effective_from, created_by
FROM catalog.price_versions WHERE sub_service_id = $1 ORDER BY effective_from DESC, id DESC
`

func (q *Queries) PriceHistory(ctx context.Context, subServiceID uuid.UUID) ([]CatalogPriceVersion, error) {
	rows, err := q.db.Query(ctx, priceHistory, subServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogPriceVersion
	for rows.Next() {
		var i CatalogPriceVersion
		if err := rows.Scan(
			&i.ID,
			&i.SubServiceID,
			&i.AmountPaisa,
			&i.EffectiveFrom,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServices = `-- name: SearchServices :many
SELECT id FROM catalog.services
WHERE published AND (lower(name_en || ' ' || name_bn) LIKE '%' || lower($1::text) || '%'
    OR word_similarity(lower($1::text), lower(name_en || ' ' || name_bn)) > 0.5)
ORDER BY word_similarity(lower($1::text), lower(name_en || ' ' || name_bn)) DESC LIMIT 20
`

func (q *Queries) SearchServices(ctx context.Context, term string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, searchServices, term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSubServices = `-- name: SearchSubServices :many
SELECT id FROM catalog.sub_services
WHERE published AND (search_text LIKE '%' || lower($1::text) || '%'
    OR word_similarity(lower($1::text), search_text) > 0.5)
ORDER BY word_similarity(lower($1::text), search_text) DESC LIMIT 30
`

func (q *Queries) SearchSubServices(ctx context.Context, term string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, searchSubServices, term)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serviceByID = `-- name: ServiceByID :one
SELECT id, category_id, name_en, name_bn, icon_key, service_model, required_level, search_radius_m,
       women_providers_only, requires_level_2, level2_checklist, sort_order, published
FROM catalog.services WHERE id = $1
`

type ServiceByIDRow struct {
	ID                 uuid.UUID
	CategoryID         uuid.UUID
	NameEn             string
	NameBn             string
	IconKey            string
	ServiceModel       string
	RequiredLevel      int32
	SearchRadiusM      int32
	WomenProvidersOnly bool
	RequiresLevel2     bool
	Level2Checklist    []byte
	SortOrder          int32
	Published          bool
}

func (q *Queries) ServiceByID(ctx context.Context, id uuid.UUID) (ServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, serviceByID, id)
	var i ServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.NameEn,
		&i.NameBn,
		&i.IconKey,
		&i.ServiceModel,
		&i.RequiredLevel,
		&i.SearchRadiusM,
		&i.WomenProvidersOnly,
		&i.RequiresLevel2,
		&i.Level2Checklist,
		&i.SortOrder,
		&i.Published,
	)
	return i, err
}

const services = `-- name: Services :many
SELECT id, category_id, name_en, name_bn, icon_key, service_model, required_level, search_radius_m,
       women_providers_only, requires_level_2, level2_checklist, sort_order, published
FROM catalog.services ORDER BY sort_order, name_en
`

type ServicesRow struct {
	ID                 uuid.UUID
	CategoryID         uuid.UUID
	NameEn             string
	NameBn             string
	IconKey            string
	ServiceModel       string
	RequiredLevel      int32
	SearchRadiusM      int32
	WomenProvidersOnly bool
	RequiresLevel2     bool
	Level2Checklist    []byte
	SortOrder          int32
	Published          bool
}

func (q *Queries) Services(ctx context.Context) ([]ServicesRow, error) {
	rows, err := q.db.Query(ctx, services)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServicesRow
	for rows.Next() {
		var i ServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.NameEn,
			&i.NameBn,
			&i.IconKey,
			&i.ServiceModel,
			&i.RequiredLevel,
			&i.SearchRadiusM,
			&i.WomenProvidersOnly,
			&i.RequiresLevel2,
			&i.Level2Checklist,
			&i.SortOrder,
			&i.Published,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subServiceByID = `-- name: SubServiceByID :one
SELECT s.id, s.service_id, s.name_en, s.name_bn, s.description, s.inclusions, s.exclusions, s.unit,
       s.max_quantity, s.sort_order, s.published, p.id AS price_version_id, p.amount_paisa
FROM catalog.sub_services s JOIN catalog.price_versions p ON p.id = s.current_price_version_id
WHERE s.id = $1
`

type SubServiceByIDRow struct {
	ID             uuid.UUID
	ServiceID      uuid.UUID
	NameEn         string
	NameBn         string
	Description    []byte
	Inclusions     []byte
	Exclusions     []byte
	Unit           string
	MaxQuantity    int32
	SortOrder      int32
	Published      bool
	PriceVersionID uuid.UUID
	AmountPaisa    int64
}

func (q *Queries) SubServiceByID(ctx context.Context, id uuid.UUID) (SubServiceByIDRow, error) {
	row := q.db.QueryRow(ctx, subServiceByID, id)
	var i SubServiceByIDRow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.NameEn,
		&i.NameBn,
		&i.Description,
		&i.Inclusions,
		&i.Exclusions,
		&i.Unit,
		&i.MaxQuantity,
		&i.SortOrder,
		&i.Published,
		&i.PriceVersionID,
		&i.AmountPaisa,
	)
	return i, err
}

const subServices = `-- name: SubServices :many
SELECT s.id, s.service_id, s.name_en, s.name_bn, s.description, s.inclusions, s.exclusions, s.unit,
       s.max_quantity, s.sort_order, s.published, p.id AS price_version_id, p.amount_paisa
FROM catalog.sub_services s JOIN catalog.price_versions p ON p.id = s.current_price_version_id
ORDER BY s.sort_order, s.name_en
`

type SubServicesRow struct {
	ID             uuid.UUID
	ServiceID      uuid.UUID
	NameEn         string
	NameBn         string
	Description    []byte
	Inclusions     []byte
	Exclusions     []byte
	Unit           string
	MaxQuantity    int32
	SortOrder      int32
	Published      bool
	PriceVersionID uuid.UUID
	AmountPaisa    int64
}

func (q *Queries) SubServices(ctx context.Context) ([]SubServicesRow, error) {
	rows, err := q.db.Query(ctx, subServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubServicesRow
	for rows.Next() {
		var i SubServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.NameEn,
			&i.NameBn,
			&i.Description,
			&i.Inclusions,
			&i.Exclusions,
			&i.Unit,
			&i.MaxQuantity,
			&i.SortOrder,
			&i.Published,
			&i.PriceVersionID,
			&i.AmountPaisa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subServicesOfService = `-- name: SubServicesOfService :many
SELECT s.id, s.service_id, s.name_en, s.name_bn, s.description, s.inclusions, s.exclusions, s.unit,
       s.max_quantity, s.sort_order, s.published, p.id AS price_version_id, p.amount_paisa
FROM catalog.sub_services s JOIN catalog.price_versions p ON p.id = s.current_price_version_id
WHERE s.service_id = $1 ORDER BY s.sort_order, s.name_en
`

type SubServicesOfServiceRow struct {
	ID             uuid.UUID
	ServiceID      uuid.UUID
	NameEn         string
	NameBn         string
	Description    []byte
	Inclusions     []byte
	Exclusions     []byte
	Unit           string
	MaxQuantity    int32
	SortOrder      int32
	Published      bool
	PriceVersionID uuid.UUID
	AmountPaisa    int64
}

func (q *Queries) SubServicesOfService(ctx context.Context, serviceID uuid.UUID) ([]SubServicesOfServiceRow, error) {
	rows, err := q.db.Query(ctx, subServicesOfService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubServicesOfServiceRow
	for rows.Next() {
		var i SubServicesOfServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.NameEn,
			&i.NameBn,
			&i.Description,
			&i.Inclusions,
			&i.Exclusions,
			&i.Unit,
			&i.MaxQuantity,
			&i.SortOrder,
			&i.Published,
			&i.PriceVersionID,
			&i.AmountPaisa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategory = `-- name: UpsertCategory :execrows
INSERT INTO catalog.categories (id, name_en, name_bn, icon_key, sort_order, published, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
ON CONFLICT (id) DO UPDATE SET name_en = excluded.name_en, name_bn = excluded.name_bn, icon_key = excluded.icon_key,
    sort_order = excluded.sort_order, published = excluded.published, updated_at = excluded.updated_at
`

type UpsertCategoryParams struct {
	ID        uuid.UUID
	NameEn    string
	NameBn    string
	IconKey   string
	SortOrder int32
	Published bool
	CreatedAt time.Time
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertCategory,
		arg.ID,
		arg.NameEn,
		arg.NameBn,
		arg.IconKey,
		arg.SortOrder,
		arg.Published,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertService = `-- name: UpsertService :execrows
INSERT INTO catalog.services (id, category_id, name_en, name_bn, icon_key, service_model, required_level, search_radius_m,
    women_providers_only, requires_level_2, level2_checklist, sort_order, published, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $14)
ON CONFLICT (id) DO UPDATE SET category_id = excluded.category_id, name_en = excluded.name_en, name_bn = excluded.name_bn,
    icon_key = excluded.icon_key, service_model = excluded.service_model, required_level = excluded.required_level,
    search_radius_m = excluded.search_radius_m, women_providers_only = excluded.women_providers_only,
    requires_level_2 = excluded.requires_level_2, level2_checklist = excluded.level2_checklist,
    sort_order = excluded.sort_order, published = excluded.published, updated_at = excluded.updated_at
`

type UpsertServiceParams struct {
	ID                 uuid.UUID
	CategoryID         uuid.UUID
	NameEn             string
	NameBn             string
	IconKey            string
	ServiceModel       string
	RequiredLevel      int32
	SearchRadiusM      int32
	WomenProvidersOnly bool
	RequiresLevel2     bool
	Level2Checklist    []byte
	SortOrder          int32
	Published          bool
	CreatedAt          time.Time
}

func (q *Queries) UpsertService(ctx context.Context, arg UpsertServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertService,
		arg.ID,
		arg.CategoryID,
		arg.NameEn,
		arg.NameBn,
		arg.IconKey,
		arg.ServiceModel,
		arg.RequiredLevel,
		arg.SearchRadiusM,
		arg.WomenProvidersOnly,
		arg.RequiresLevel2,
		arg.Level2Checklist,
		arg.SortOrder,
		arg.Published,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSubService = `-- name: UpsertSubService :execrows
INSERT INTO catalog.sub_services (id, service_id, name_en, name_bn, description, inclusions, exclusions, unit,
    max_quantity, sort_order, published, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $12)
ON CONFLICT (id) DO UPDATE SET service_id = excluded.service_id, name_en = excluded.name_en, name_bn = excluded.name_bn,
    description = excluded.description, inclusions = excluded.inclusions, exclusions = excluded.exclusions,
    unit = excluded.unit, max_quantity = excluded.max_quantity, sort_order = excluded.sort_order,
    published = excluded.published, updated_at = excluded.updated_at
`

type UpsertSubServiceParams struct {
	ID          uuid.UUID
	ServiceID   uuid.UUID
	NameEn      string
	NameBn      string
	Description []byte
	Inclusions  []byte
	Exclusions  []byte
	Unit        string
	MaxQuantity int32
	SortOrder   int32
	Published   bool
	CreatedAt   time.Time
}

func (q *Queries) UpsertSubService(ctx context.Context, arg UpsertSubServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertSubService,
		arg.ID,
		arg.ServiceID,
		arg.NameEn,
		arg.NameBn,
		arg.Description,
		arg.Inclusions,
		arg.Exclusions,
		arg.Unit,
		arg.MaxQuantity,
		arg.SortOrder,
		arg.Published,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const version = `-- name: Version :one
SELECT version FROM catalog.catalog_version
`

func (q *Queries) Version(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, version)
	var version int64
	err := row.Scan(&version)
	return version, err
}
