-- +goose Up
-- RBAC seed from docs/build/02-architecture.md §6 and docs/build/05-screens.md.
-- Super admins edit these rows from the admin panel afterwards (A-10).

INSERT INTO identity.roles (name, description, is_admin) VALUES
    ('customer', 'Customer (PAO app)', false),
    ('provider', 'Service provider (PAO Partner app)', false),
    ('verifier', 'Verifier / ops agent', true),
    ('catalog_manager', 'Catalog manager', true),
    ('support_agent', 'Support agent', true),
    ('super_admin', 'Super admin', true);

INSERT INTO identity.permissions (name, description) VALUES
    ('profile:manage:own', 'Read and edit own customer profile'),
    ('address:manage:own', 'Manage own saved addresses'),
    ('catalog:read', 'Browse the published catalog'),
    ('provider:browse', 'Search providers and view public profiles'),
    ('booking:create', 'Request a booking'),
    ('booking:read:own', 'Read own bookings'),
    ('booking:cancel:own', 'Cancel own bookings'),
    ('booking:update:own', 'Decide extra items on own bookings'),
    ('review:create', 'Rate the other side after a completed booking'),
    ('complaint:create', 'Report a problem on a booking'),
    ('notification:read:own', 'Read own notifications'),
    ('device:register', 'Register a device for push notifications'),
    ('media:upload', 'Upload files through signed URLs'),
    ('provider:manage:own', 'Manage own provider profile, enrolment and presence'),
    ('verification:submit', 'Submit enrolment for verification'),
    ('job:read:own', 'Read own requests and jobs'),
    ('job:respond', 'Accept, reject or cancel requests'),
    ('job:progress', 'Move own jobs through their states'),
    ('earnings:read:own', 'Read own earnings'),
    ('verification:review', 'Review and decide verification items'),
    ('verification:docs:view', 'View verification documents (audited)'),
    ('provider:read', 'Read provider records'),
    ('provider:manage', 'Suspend, ban or reinstate providers'),
    ('level2:manage', 'Schedule and record Level 2 sessions'),
    ('catalog:manage', 'Edit the catalog and prices'),
    ('settings:read', 'Read platform settings'),
    ('settings:manage', 'Change platform settings'),
    ('complaint:manage', 'Work the complaints queue'),
    ('booking:read:any', 'Read any booking'),
    ('customer:read', 'Read customer records'),
    ('customer:manage', 'Suspend, ban or reinstate customers'),
    ('dashboard:read', 'See the admin dashboard'),
    ('admin_user:manage', 'Invite and manage admin users'),
    ('audit:read', 'Read the audit log'),
    ('role:manage', 'Edit role permissions and screens');

INSERT INTO identity.role_permissions (role, permission) VALUES
    ('customer', 'profile:manage:own'),
    ('customer', 'address:manage:own'),
    ('customer', 'catalog:read'),
    ('customer', 'provider:browse'),
    ('customer', 'booking:create'),
    ('customer', 'booking:read:own'),
    ('customer', 'booking:cancel:own'),
    ('customer', 'booking:update:own'),
    ('customer', 'review:create'),
    ('customer', 'complaint:create'),
    ('customer', 'notification:read:own'),
    ('customer', 'device:register'),
    ('customer', 'media:upload'),
    ('provider', 'provider:manage:own'),
    ('provider', 'verification:submit'),
    ('provider', 'catalog:read'),
    ('provider', 'job:read:own'),
    ('provider', 'job:respond'),
    ('provider', 'job:progress'),
    ('provider', 'earnings:read:own'),
    ('provider', 'review:create'),
    ('provider', 'complaint:create'),
    ('provider', 'notification:read:own'),
    ('provider', 'device:register'),
    ('provider', 'media:upload'),
    ('verifier', 'verification:review'),
    ('verifier', 'verification:docs:view'),
    ('verifier', 'provider:read'),
    ('verifier', 'level2:manage'),
    ('verifier', 'dashboard:read'),
    ('catalog_manager', 'catalog:manage'),
    ('catalog_manager', 'settings:read'),
    ('catalog_manager', 'dashboard:read'),
    ('support_agent', 'complaint:manage'),
    ('support_agent', 'booking:read:any'),
    ('support_agent', 'customer:read'),
    ('support_agent', 'provider:read'),
    ('support_agent', 'dashboard:read'),
    ('super_admin', 'address:manage:own'),
    ('super_admin', 'admin_user:manage'),
    ('super_admin', 'audit:read'),
    ('super_admin', 'booking:cancel:own'),
    ('super_admin', 'booking:create'),
    ('super_admin', 'booking:read:any'),
    ('super_admin', 'booking:read:own'),
    ('super_admin', 'booking:update:own'),
    ('super_admin', 'catalog:manage'),
    ('super_admin', 'catalog:read'),
    ('super_admin', 'complaint:create'),
    ('super_admin', 'complaint:manage'),
    ('super_admin', 'customer:manage'),
    ('super_admin', 'customer:read'),
    ('super_admin', 'dashboard:read'),
    ('super_admin', 'device:register'),
    ('super_admin', 'earnings:read:own'),
    ('super_admin', 'job:progress'),
    ('super_admin', 'job:read:own'),
    ('super_admin', 'job:respond'),
    ('super_admin', 'level2:manage'),
    ('super_admin', 'media:upload'),
    ('super_admin', 'notification:read:own'),
    ('super_admin', 'profile:manage:own'),
    ('super_admin', 'provider:browse'),
    ('super_admin', 'provider:manage'),
    ('super_admin', 'provider:manage:own'),
    ('super_admin', 'provider:read'),
    ('super_admin', 'review:create'),
    ('super_admin', 'role:manage'),
    ('super_admin', 'settings:manage'),
    ('super_admin', 'settings:read'),
    ('super_admin', 'verification:docs:view'),
    ('super_admin', 'verification:review'),
    ('super_admin', 'verification:submit');

INSERT INTO identity.screens (id, app, name) VALUES
    ('C01', 'customer', 'Splash'),
    ('C02', 'customer', 'Onboarding slide 1'),
    ('C31', 'customer', 'Onboarding slide 2'),
    ('C32', 'customer', 'Onboarding slide 3 and language'),
    ('C03', 'customer', 'Phone entry'),
    ('C04', 'customer', 'OTP'),
    ('C33', 'customer', 'OTP wrong code'),
    ('C05', 'customer', 'Profile setup'),
    ('C06', 'customer', 'Set location'),
    ('C34', 'customer', 'Location permission'),
    ('C07', 'customer', 'Home'),
    ('C35', 'customer', 'Area not covered'),
    ('C36', 'customer', 'Offline'),
    ('C37', 'customer', 'All services'),
    ('C08', 'customer', 'Search results'),
    ('C38', 'customer', 'No search results'),
    ('C09', 'customer', 'Service detail'),
    ('C43', 'customer', 'Service detail: home salon'),
    ('C44', 'customer', 'Service detail: driver hire'),
    ('C10', 'customer', 'Provider list'),
    ('C39', 'customer', 'Provider list empty'),
    ('C40', 'customer', 'Sort and filter'),
    ('C11', 'customer', 'Provider profile'),
    ('C41', 'customer', 'Badge explainer'),
    ('C42', 'customer', 'All reviews'),
    ('C12', 'customer', 'Booking setup: scheduled'),
    ('C45', 'customer', 'Booking setup: ASAP'),
    ('C46', 'customer', 'Choose address'),
    ('C13', 'customer', 'Waiting for provider'),
    ('C13b', 'customer', 'Request timed out'),
    ('C47', 'customer', 'Request declined'),
    ('C48', 'customer', 'Scheduled booking confirmed'),
    ('C49', 'customer', 'Booking accepted'),
    ('C14', 'customer', 'Provider on the way'),
    ('C50', 'customer', 'Provider arrived'),
    ('C51', 'customer', 'Job in progress'),
    ('C15', 'customer', 'Extra items approval'),
    ('C52', 'customer', 'Cancel booking'),
    ('C53', 'customer', 'Booking cancelled'),
    ('C54', 'customer', 'Cannot cancel'),
    ('C16', 'customer', 'Job completed'),
    ('C17', 'customer', 'Rate provider'),
    ('C55', 'customer', 'Rating thanks'),
    ('C18', 'customer', 'Bookings: upcoming'),
    ('C18b', 'customer', 'Bookings: past'),
    ('C58', 'customer', 'Bookings empty'),
    ('C19', 'customer', 'Booking detail'),
    ('C57', 'customer', 'Booking detail: cancelled'),
    ('C64', 'customer', 'Receipt'),
    ('C20', 'customer', 'Report a problem'),
    ('C56', 'customer', 'Report submitted'),
    ('C21', 'customer', 'Notifications'),
    ('C59', 'customer', 'Notifications empty'),
    ('C60', 'customer', 'Push payloads'),
    ('C22', 'customer', 'Account'),
    ('C23', 'customer', 'Edit profile'),
    ('C24', 'customer', 'Saved addresses'),
    ('C25', 'customer', 'Add or edit address'),
    ('C26', 'customer', 'Language'),
    ('C27', 'customer', 'Help and support'),
    ('C28', 'customer', 'Terms and privacy'),
    ('C29', 'customer', 'Delete account'),
    ('C61', 'customer', 'Delete account OTP'),
    ('C62', 'customer', 'Account deleted'),
    ('C30', 'customer', 'Log out'),
    ('C63', 'customer', 'Welcome back'),
    ('M01', 'partner', 'Splash'),
    ('M02', 'partner', 'Onboarding and language'),
    ('M03', 'partner', 'Phone entry'),
    ('M04', 'partner', 'OTP'),
    ('M05', 'partner', 'Enrolment: personal info'),
    ('M06', 'partner', 'Enrolment: services'),
    ('M07', 'partner', 'Enrolment: service area'),
    ('M08', 'partner', 'Enrolment: NID'),
    ('M09', 'partner', 'Enrolment: selfie'),
    ('M10', 'partner', 'Enrolment: police clearance'),
    ('M11', 'partner', 'Enrolment: skill proof'),
    ('M12', 'partner', 'Enrolment: emergency contact'),
    ('M13', 'partner', 'Enrolment: code of conduct'),
    ('M14', 'partner', 'Verification status'),
    ('M15', 'partner', 'Home'),
    ('M15b', 'partner', 'Home: requests paused'),
    ('M16', 'partner', 'Incoming request'),
    ('M17', 'partner', 'Active job'),
    ('M18', 'partner', 'Enter start code'),
    ('M19', 'partner', 'Add extra items'),
    ('M20', 'partner', 'Complete job'),
    ('M21', 'partner', 'Rate customer'),
    ('M23', 'partner', 'Jobs'),
    ('M24', 'partner', 'Job detail'),
    ('M25', 'partner', 'Report a problem'),
    ('M26', 'partner', 'Earnings summary'),
    ('M27', 'partner', 'Earnings by job'),
    ('M28', 'partner', 'Profile'),
    ('M29', 'partner', 'Public profile'),
    ('M30', 'partner', 'Reviews'),
    ('M31', 'partner', 'Documents and expiry'),
    ('M32', 'partner', 'Badge and level'),
    ('M33', 'partner', 'Services and area'),
    ('M34', 'partner', 'Language'),
    ('M35', 'partner', 'Help'),
    ('M36', 'partner', 'Log out'),
    ('A01', 'admin', 'Login and 2FA'),
    ('A02', 'admin', 'Dashboard'),
    ('A03', 'admin', 'Catalog tree'),
    ('A04', 'admin', 'Service editor'),
    ('A05', 'admin', 'Verification queue'),
    ('A06', 'admin', 'Verification review'),
    ('A07', 'admin', 'Level 2 session'),
    ('A08', 'admin', 'Providers'),
    ('A09', 'admin', 'Customers'),
    ('A10', 'admin', 'Bookings monitor'),
    ('A11', 'admin', 'Complaints'),
    ('A12', 'admin', 'Settings, admin users, roles and audit log');

INSERT INTO identity.role_screens (role, screen_id) VALUES
    ('customer', 'C01'),
    ('customer', 'C02'),
    ('customer', 'C31'),
    ('customer', 'C32'),
    ('customer', 'C03'),
    ('customer', 'C04'),
    ('customer', 'C33'),
    ('customer', 'C05'),
    ('customer', 'C06'),
    ('customer', 'C34'),
    ('customer', 'C07'),
    ('customer', 'C35'),
    ('customer', 'C36'),
    ('customer', 'C37'),
    ('customer', 'C08'),
    ('customer', 'C38'),
    ('customer', 'C09'),
    ('customer', 'C43'),
    ('customer', 'C44'),
    ('customer', 'C10'),
    ('customer', 'C39'),
    ('customer', 'C40'),
    ('customer', 'C11'),
    ('customer', 'C41'),
    ('customer', 'C42'),
    ('customer', 'C12'),
    ('customer', 'C45'),
    ('customer', 'C46'),
    ('customer', 'C13'),
    ('customer', 'C13b'),
    ('customer', 'C47'),
    ('customer', 'C48'),
    ('customer', 'C49'),
    ('customer', 'C14'),
    ('customer', 'C50'),
    ('customer', 'C51'),
    ('customer', 'C15'),
    ('customer', 'C52'),
    ('customer', 'C53'),
    ('customer', 'C54'),
    ('customer', 'C16'),
    ('customer', 'C17'),
    ('customer', 'C55'),
    ('customer', 'C18'),
    ('customer', 'C18b'),
    ('customer', 'C58'),
    ('customer', 'C19'),
    ('customer', 'C57'),
    ('customer', 'C64'),
    ('customer', 'C20'),
    ('customer', 'C56'),
    ('customer', 'C21'),
    ('customer', 'C59'),
    ('customer', 'C60'),
    ('customer', 'C22'),
    ('customer', 'C23'),
    ('customer', 'C24'),
    ('customer', 'C25'),
    ('customer', 'C26'),
    ('customer', 'C27'),
    ('customer', 'C28'),
    ('customer', 'C29'),
    ('customer', 'C61'),
    ('customer', 'C62'),
    ('customer', 'C30'),
    ('customer', 'C63'),
    ('provider', 'M01'),
    ('provider', 'M02'),
    ('provider', 'M03'),
    ('provider', 'M04'),
    ('provider', 'M05'),
    ('provider', 'M06'),
    ('provider', 'M07'),
    ('provider', 'M08'),
    ('provider', 'M09'),
    ('provider', 'M10'),
    ('provider', 'M11'),
    ('provider', 'M12'),
    ('provider', 'M13'),
    ('provider', 'M14'),
    ('provider', 'M15'),
    ('provider', 'M15b'),
    ('provider', 'M16'),
    ('provider', 'M17'),
    ('provider', 'M18'),
    ('provider', 'M19'),
    ('provider', 'M20'),
    ('provider', 'M21'),
    ('provider', 'M23'),
    ('provider', 'M24'),
    ('provider', 'M25'),
    ('provider', 'M26'),
    ('provider', 'M27'),
    ('provider', 'M28'),
    ('provider', 'M29'),
    ('provider', 'M30'),
    ('provider', 'M31'),
    ('provider', 'M32'),
    ('provider', 'M33'),
    ('provider', 'M34'),
    ('provider', 'M35'),
    ('provider', 'M36'),
    ('verifier', 'A01'),
    ('verifier', 'A02'),
    ('verifier', 'A05'),
    ('verifier', 'A06'),
    ('verifier', 'A07'),
    ('verifier', 'A08'),
    ('catalog_manager', 'A01'),
    ('catalog_manager', 'A02'),
    ('catalog_manager', 'A03'),
    ('catalog_manager', 'A04'),
    ('support_agent', 'A01'),
    ('support_agent', 'A02'),
    ('support_agent', 'A08'),
    ('support_agent', 'A09'),
    ('support_agent', 'A10'),
    ('support_agent', 'A11'),
    ('super_admin', 'A01'),
    ('super_admin', 'A02'),
    ('super_admin', 'A03'),
    ('super_admin', 'A04'),
    ('super_admin', 'A05'),
    ('super_admin', 'A06'),
    ('super_admin', 'A07'),
    ('super_admin', 'A08'),
    ('super_admin', 'A09'),
    ('super_admin', 'A10'),
    ('super_admin', 'A11'),
    ('super_admin', 'A12');

-- +goose Down
DELETE FROM identity.role_screens;
DELETE FROM identity.screens;
DELETE FROM identity.role_permissions;
DELETE FROM identity.permissions;
DELETE FROM identity.roles;
