// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type MediaObject struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Purpose     string
	ContentType string
	SizeBytes   int64
	Bucket      string
	ObjectKey   string
	Status      string
	Attached    bool
	CreatedAt   time.Time
	ConfirmedAt *time.Time
}

type MediaOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type MediaProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}
