// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createObject = `-- name: CreateObject :exec
INSERT INTO media.objects (id, owner_id, purpose, content_type, size_bytes, bucket, object_key, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', $8)
`

type CreateObjectParams struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Purpose     string
	ContentType string
	SizeBytes   int64
	Bucket      string
	ObjectKey   string
	CreatedAt   time.Time
}

func (q *Queries) CreateObject(ctx context.Context, arg CreateObjectParams) error {
	_, err := q.db.Exec(ctx, createObject,
		arg.ID,
		arg.OwnerID,
		arg.Purpose,
		arg.ContentType,
		arg.SizeBytes,
		arg.Bucket,
		arg.ObjectKey,
		arg.CreatedAt,
	)
	return err
}

const deleteObject = `-- name: DeleteObject :exec
DELETE FROM media.objects WHERE id = $1
`

func (q *Queries) DeleteObject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteObject, id)
	return err
}

const markAttached = `-- name: MarkAttached :execrows
UPDATE media.objects SET attached = true WHERE id = $1
`

func (q *Queries) MarkAttached(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAttached, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markConfirmed = `-- name: MarkConfirmed :exec
UPDATE media.objects SET status = 'confirmed', confirmed_at = $2 WHERE id = $1
`

type MarkConfirmedParams struct {
	ID          uuid.UUID
	ConfirmedAt *time.Time
}

func (q *Queries) MarkConfirmed(ctx context.Context, arg MarkConfirmedParams) error {
	_, err := q.db.Exec(ctx, markConfirmed, arg.ID, arg.ConfirmedAt)
	return err
}

const objectByID = `-- name: ObjectByID :one
SELECT id, owner_id, purpose, content_type, size_bytes, bucket, object_key, status, attached, created_at
FROM media.objects WHERE id = $1
`

type ObjectByIDRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Purpose     string
	ContentType string
	SizeBytes   int64
	Bucket      string
	ObjectKey   string
	Status      string
	Attached    bool
	CreatedAt   time.Time
}

func (q *Queries) ObjectByID(ctx context.Context, id uuid.UUID) (ObjectByIDRow, error) {
	row := q.db.QueryRow(ctx, objectByID, id)
	var i ObjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Purpose,
		&i.ContentType,
		&i.SizeBytes,
		&i.Bucket,
		&i.ObjectKey,
		&i.Status,
		&i.Attached,
		&i.CreatedAt,
	)
	return i, err
}

const orphans = `-- name: Orphans :many
SELECT id, owner_id, purpose, content_type, size_bytes, bucket, object_key, status, attached, created_at
FROM media.objects WHERE NOT attached AND created_at < $1 ORDER BY created_at LIMIT 500
`

type OrphansRow struct {
	ID          uuid.UUID
	OwnerID     uuid.UUID
	Purpose     string
	ContentType string
	SizeBytes   int64
	Bucket      string
	ObjectKey   string
	Status      string
	Attached    bool
	CreatedAt   time.Time
}

func (q *Queries) Orphans(ctx context.Context, createdAt time.Time) ([]OrphansRow, error) {
	rows, err := q.db.Query(ctx, orphans, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrphansRow
	for rows.Next() {
		var i OrphansRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Purpose,
			&i.ContentType,
			&i.SizeBytes,
			&i.Bucket,
			&i.ObjectKey,
			&i.Status,
			&i.Attached,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
