// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type BookingBooking struct {
	ID                   uuid.UUID
	Number               int64
	CustomerID           uuid.UUID
	ProviderID           uuid.UUID
	ServiceID            uuid.UUID
	ServiceNameEn        string
	ServiceNameBn        string
	ServiceModel         string
	CustomerName         string
	CustomerPhone        string
	ProviderName         string
	ProviderPhone        string
	AddressID            uuid.UUID
	AddressArea          string
	AddressLine1         string
	AddressLine2         string
	AddressLocation      interface{}
	Note                 string
	Status               string
	Timing               string
	ScheduledAt          *time.Time
	EndsAt               *time.Time
	AcceptDeadline       time.Time
	TotalPaisa           int64
	StartCode            string
	StartCodeAttempts    int32
	StartCodeLockedUntil *time.Time
	CashReceived         bool
	IdempotencyKey       string
	CancelReason         string
	CancelledBy          *string
	RejectReason         string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	AcceptedAt           *time.Time
	StartedAt            *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
}

type BookingBookingItem struct {
	ID             uuid.UUID
	BookingID      uuid.UUID
	ProposalID     *uuid.UUID
	SubServiceID   uuid.UUID
	PriceVersionID uuid.UUID
	NameEn         string
	NameBn         string
	Unit           string
	Quantity       int32
	UnitPricePaisa int64
	TotalPaisa     int64
	Extra          bool
	Position       int32
}

type BookingExtrasProposal struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	Status     string
	AddedPaisa int64
	ProposedAt time.Time
	DecidedAt  *time.Time
}

type BookingOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type BookingProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type BookingTimeline struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	Status    string
	Actor     string
	Reason    string
	At        time.Time
}
