// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bookingByID = `-- name: BookingByID :one
SELECT id, number, customer_id, provider_id, service_id, service_name_en, service_name_bn, service_model, customer_name,
    customer_phone, provider_name, provider_phone, address_id, address_area, address_line1, address_line2,
    ST_Y(address_location::geometry)::float8 AS lat, ST_X(address_location::geometry)::float8 AS lng, note, status, timing,
    scheduled_at, ends_at, accept_deadline, total_paisa, start_code, start_code_attempts, start_code_locked_until,
    cash_received, idempotency_key, cancel_reason, cancelled_by, reject_reason, created_at, accepted_at, started_at,
    completed_at, cancelled_at
FROM booking.bookings WHERE id = $1
`

type BookingByIDRow struct {
	ID                   uuid.UUID
	Number               int64
	CustomerID           uuid.UUID
	ProviderID           uuid.UUID
	ServiceID            uuid.UUID
	ServiceNameEn        string
	ServiceNameBn        string
	ServiceModel         string
	CustomerName         string
	CustomerPhone        string
	ProviderName         string
	ProviderPhone        string
	AddressID            uuid.UUID
	AddressArea          string
	AddressLine1         string
	AddressLine2         string
	Lat                  float64
	Lng                  float64
	Note                 string
	Status               string
	Timing               string
	ScheduledAt          *time.Time
	EndsAt               *time.Time
	AcceptDeadline       time.Time
	TotalPaisa           int64
	StartCode            string
	StartCodeAttempts    int32
	StartCodeLockedUntil *time.Time
	CashReceived         bool
	IdempotencyKey       string
	CancelReason         string
	CancelledBy          *string
	RejectReason         string
	CreatedAt            time.Time
	AcceptedAt           *time.Time
	StartedAt            *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
}

func (q *Queries) BookingByID(ctx context.Context, id uuid.UUID) (BookingByIDRow, error) {
	row := q.db.QueryRow(ctx, bookingByID, id)
	var i BookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.CustomerID,
		&i.ProviderID,
		&i.ServiceID,
		&i.ServiceNameEn,
		&i.ServiceNameBn,
		&i.ServiceModel,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.ProviderName,
		&i.ProviderPhone,
		&i.AddressID,
		&i.AddressArea,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.Lat,
		&i.Lng,
		&i.Note,
		&i.Status,
		&i.Timing,
		&i.ScheduledAt,
		&i.EndsAt,
		&i.AcceptDeadline,
		&i.TotalPaisa,
		&i.StartCode,
		&i.StartCodeAttempts,
		&i.StartCodeLockedUntil,
		&i.CashReceived,
		&i.IdempotencyKey,
		&i.CancelReason,
		&i.CancelledBy,
		&i.RejectReason,
		&i.CreatedAt,
		&i.AcceptedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CancelledAt,
	)
	return i, err
}

const bookingIDByKey = `-- name: BookingIDByKey :one
SELECT id FROM booking.bookings WHERE customer_id = $1 AND idempotency_key = $2
`

type BookingIDByKeyParams struct {
	CustomerID     uuid.UUID
	IdempotencyKey string
}

func (q *Queries) BookingIDByKey(ctx context.Context, arg BookingIDByKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, bookingIDByKey, arg.CustomerID, arg.IdempotencyKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const countActive = `-- name: CountActive :one
SELECT count(*) FROM booking.bookings
WHERE provider_id = $1 AND id <> $2 AND status IN ('accepted', 'on_the_way', 'arrived', 'in_progress')
`

type CountActiveParams struct {
	ProviderID uuid.UUID
	ExceptID   uuid.UUID
}

func (q *Queries) CountActive(ctx context.Context, arg CountActiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActive, arg.ProviderID, arg.ExceptID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dueRequests = `-- name: DueRequests :many
SELECT id FROM booking.bookings WHERE status = 'requested' AND accept_deadline <= $1 ORDER BY accept_deadline LIMIT 500
`

func (q *Queries) DueRequests(ctx context.Context, acceptDeadline time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dueRequests, acceptDeadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const earningsByDay = `-- name: EarningsByDay :many
SELECT (completed_at AT TIME ZONE 'Asia/Dhaka')::date AS day, sum(total_paisa)::bigint AS total, count(*)::int AS jobs
FROM booking.bookings
WHERE provider_id = $1 AND status = 'completed' AND completed_at >= $2 AND completed_at < $3
GROUP BY day ORDER BY day
`

type EarningsByDayParams struct {
	ProviderID uuid.UUID
	FromAt     *time.Time
	UntilAt    *time.Time
}

type EarningsByDayRow struct {
	Day   time.Time
	Total int64
	Jobs  int32
}

func (q *Queries) EarningsByDay(ctx context.Context, arg EarningsByDayParams) ([]EarningsByDayRow, error) {
	rows, err := q.db.Query(ctx, earningsByDay, arg.ProviderID, arg.FromAt, arg.UntilAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EarningsByDayRow
	for rows.Next() {
		var i EarningsByDayRow
		if err := rows.Scan(&i.Day, &i.Total, &i.Jobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const earningsJobs = `-- name: EarningsJobs :many
SELECT id, number, completed_at::timestamptz AS completed_at, service_name_en, service_name_bn, total_paisa
FROM booking.bookings
WHERE provider_id = $1 AND status = 'completed' AND completed_at >= $2 AND completed_at < $3
  AND ($4::timestamptz IS NULL OR (completed_at, id) < ($4, $5::uuid))
ORDER BY completed_at DESC, id DESC LIMIT $6
`

type EarningsJobsParams struct {
	ProviderID uuid.UUID
	FromAt     *time.Time
	UntilAt    *time.Time
	BeforeAt   *time.Time
	BeforeID   uuid.UUID
	MaxRows    int32
}

type EarningsJobsRow struct {
	ID            uuid.UUID
	Number        int64
	CompletedAt   time.Time
	ServiceNameEn string
	ServiceNameBn string
	TotalPaisa    int64
}

func (q *Queries) EarningsJobs(ctx context.Context, arg EarningsJobsParams) ([]EarningsJobsRow, error) {
	rows, err := q.db.Query(ctx, earningsJobs,
		arg.ProviderID,
		arg.FromAt,
		arg.UntilAt,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EarningsJobsRow
	for rows.Next() {
		var i EarningsJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.CompletedAt,
			&i.ServiceNameEn,
			&i.ServiceNameBn,
			&i.TotalPaisa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO booking.bookings (id, customer_id, provider_id, service_id, service_name_en, service_name_bn, service_model,
    customer_name, customer_phone, provider_name, provider_phone, address_id, address_area, address_line1, address_line2,
    address_location, note, status, timing, scheduled_at, ends_at, accept_deadline, total_paisa, start_code,
    idempotency_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13, $14,
    $15, ST_SetSRID(ST_MakePoint($16::float8, $17::float8), 4326)::geography,
    $18, $19, $20, $21, $22, $23,
    $24, $25, $26, $27, $27)
RETURNING number
`

type InsertBookingParams struct {
	ID             uuid.UUID
	CustomerID     uuid.UUID
	ProviderID     uuid.UUID
	ServiceID      uuid.UUID
	ServiceNameEn  string
	ServiceNameBn  string
	ServiceModel   string
	CustomerName   string
	CustomerPhone  string
	ProviderName   string
	ProviderPhone  string
	AddressID      uuid.UUID
	AddressArea    string
	AddressLine1   string
	AddressLine2   string
	Lng            float64
	Lat            float64
	Note           string
	Status         string
	Timing         string
	ScheduledAt    *time.Time
	EndsAt         *time.Time
	AcceptDeadline time.Time
	TotalPaisa     int64
	StartCode      string
	IdempotencyKey string
	CreatedAt      time.Time
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.ID,
		arg.CustomerID,
		arg.ProviderID,
		arg.ServiceID,
		arg.ServiceNameEn,
		arg.ServiceNameBn,
		arg.ServiceModel,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.ProviderName,
		arg.ProviderPhone,
		arg.AddressID,
		arg.AddressArea,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Lng,
		arg.Lat,
		arg.Note,
		arg.Status,
		arg.Timing,
		arg.ScheduledAt,
		arg.EndsAt,
		arg.AcceptDeadline,
		arg.TotalPaisa,
		arg.StartCode,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var number int64
	err := row.Scan(&number)
	return number, err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO booking.booking_items (id, booking_id, proposal_id, sub_service_id, price_version_id, name_en, name_bn, unit,
    quantity, unit_price_paisa, total_paisa, extra, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) ON CONFLICT (id) DO NOTHING
`

type InsertItemParams struct {
	ID             uuid.UUID
	BookingID      uuid.UUID
	ProposalID     *uuid.UUID
	SubServiceID   uuid.UUID
	PriceVersionID uuid.UUID
	NameEn         string
	NameBn         string
	Unit           string
	Quantity       int32
	UnitPricePaisa int64
	TotalPaisa     int64
	Extra          bool
	Position       int32
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.Exec(ctx, insertItem,
		arg.ID,
		arg.BookingID,
		arg.ProposalID,
		arg.SubServiceID,
		arg.PriceVersionID,
		arg.NameEn,
		arg.NameBn,
		arg.Unit,
		arg.Quantity,
		arg.UnitPricePaisa,
		arg.TotalPaisa,
		arg.Extra,
		arg.Position,
	)
	return err
}

const insertTimeline = `-- name: InsertTimeline :exec
INSERT INTO booking.timeline (id, booking_id, status, actor, reason, at) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTimelineParams struct {
	ID        uuid.UUID
	BookingID uuid.UUID
	Status    string
	Actor     string
	Reason    string
	At        time.Time
}

func (q *Queries) InsertTimeline(ctx context.Context, arg InsertTimelineParams) error {
	_, err := q.db.Exec(ctx, insertTimeline,
		arg.ID,
		arg.BookingID,
		arg.Status,
		arg.Actor,
		arg.Reason,
		arg.At,
	)
	return err
}

const itemsByBooking = `-- name: ItemsByBooking :many
SELECT id, proposal_id, sub_service_id, price_version_id, name_en, name_bn, unit, quantity, unit_price_paisa, total_paisa,
    extra, position
FROM booking.booking_items WHERE booking_id = $1 ORDER BY position, id
`

type ItemsByBookingRow struct {
	ID             uuid.UUID
	ProposalID     *uuid.UUID
	SubServiceID   uuid.UUID
	PriceVersionID uuid.UUID
	NameEn         string
	NameBn         string
	Unit           string
	Quantity       int32
	UnitPricePaisa int64
	TotalPaisa     int64
	Extra          bool
	Position       int32
}

func (q *Queries) ItemsByBooking(ctx context.Context, bookingID uuid.UUID) ([]ItemsByBookingRow, error) {
	rows, err := q.db.Query(ctx, itemsByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemsByBookingRow
	for rows.Next() {
		var i ItemsByBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.SubServiceID,
			&i.PriceVersionID,
			&i.NameEn,
			&i.NameBn,
			&i.Unit,
			&i.Quantity,
			&i.UnitPricePaisa,
			&i.TotalPaisa,
			&i.Extra,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookings = `-- name: ListBookings :many
SELECT id, number, status, service_name_en, service_name_bn, customer_name, provider_name, timing, scheduled_at, total_paisa, created_at
FROM booking.bookings
WHERE (CASE WHEN $1::bool THEN provider_id ELSE customer_id END) = $2
  AND (status = ANY($3::text[]))
  AND ($4::timestamptz IS NULL OR (created_at, id) < ($4, $5::uuid))
ORDER BY created_at DESC, id DESC LIMIT $6
`

type ListBookingsParams struct {
	AsProvider bool
	PartyID    uuid.UUID
	Statuses   []string
	BeforeAt   *time.Time
	BeforeID   uuid.UUID
	MaxRows    int32
}

type ListBookingsRow struct {
	ID            uuid.UUID
	Number        int64
	Status        string
	ServiceNameEn string
	ServiceNameBn string
	CustomerName  string
	ProviderName  string
	Timing        string
	ScheduledAt   *time.Time
	TotalPaisa    int64
	CreatedAt     time.Time
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.AsProvider,
		arg.PartyID,
		arg.Statuses,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBookingsRow
	for rows.Next() {
		var i ListBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.ServiceNameEn,
			&i.ServiceNameBn,
			&i.CustomerName,
			&i.ProviderName,
			&i.Timing,
			&i.ScheduledAt,
			&i.TotalPaisa,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBooking = `-- name: LockBooking :one
SELECT provider_id FROM booking.bookings WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockBooking(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockBooking, id)
	var provider_id uuid.UUID
	err := row.Scan(&provider_id)
	return provider_id, err
}

const lockProvider = `-- name: LockProvider :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::uuid::text, 0))
`

func (q *Queries) LockProvider(ctx context.Context, providerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockProvider, providerID)
	return err
}

const proposalsByBooking = `-- name: ProposalsByBooking :many
SELECT id, status, added_paisa, proposed_at, decided_at FROM booking.extras_proposals WHERE booking_id = $1 ORDER BY proposed_at, id
`

type ProposalsByBookingRow struct {
	ID         uuid.UUID
	Status     string
	AddedPaisa int64
	ProposedAt time.Time
	DecidedAt  *time.Time
}

func (q *Queries) ProposalsByBooking(ctx context.Context, bookingID uuid.UUID) ([]ProposalsByBookingRow, error) {
	rows, err := q.db.Query(ctx, proposalsByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProposalsByBookingRow
	for rows.Next() {
		var i ProposalsByBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.AddedPaisa,
			&i.ProposedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerStats = `-- name: ProviderStats :one
SELECT count(*) FILTER (WHERE status = 'completed')::int AS completed,
    count(*) FILTER (WHERE status = 'cancelled' AND cancelled_by = 'provider' AND accepted_at IS NOT NULL AND cancelled_at > $1)::int AS cancellations
FROM booking.bookings WHERE provider_id = $2
`

type ProviderStatsParams struct {
	Since      *time.Time
	ProviderID uuid.UUID
}

type ProviderStatsRow struct {
	Completed     int32
	Cancellations int32
}

func (q *Queries) ProviderStats(ctx context.Context, arg ProviderStatsParams) (ProviderStatsRow, error) {
	row := q.db.QueryRow(ctx, providerStats, arg.Since, arg.ProviderID)
	var i ProviderStatsRow
	err := row.Scan(&i.Completed, &i.Cancellations)
	return i, err
}

const timelineByBooking = `-- name: TimelineByBooking :many
SELECT id, status, actor, reason, at FROM booking.timeline WHERE booking_id = $1 ORDER BY at, id
`

type TimelineByBookingRow struct {
	ID     uuid.UUID
	Status string
	Actor  string
	Reason string
	At     time.Time
}

func (q *Queries) TimelineByBooking(ctx context.Context, bookingID uuid.UUID) ([]TimelineByBookingRow, error) {
	rows, err := q.db.Query(ctx, timelineByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimelineByBookingRow
	for rows.Next() {
		var i TimelineByBookingRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Actor,
			&i.Reason,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :exec
UPDATE booking.bookings SET status = $2, total_paisa = $3, start_code_attempts = $4, start_code_locked_until = $5,
    cash_received = $6, cancel_reason = $7, cancelled_by = $8, reject_reason = $9, accepted_at = $10, started_at = $11,
    completed_at = $12, cancelled_at = $13, updated_at = $14, start_code = $15
WHERE id = $1
`

type UpdateBookingParams struct {
	ID                   uuid.UUID
	Status               string
	TotalPaisa           int64
	StartCodeAttempts    int32
	StartCodeLockedUntil *time.Time
	CashReceived         bool
	CancelReason         string
	CancelledBy          *string
	RejectReason         string
	AcceptedAt           *time.Time
	StartedAt            *time.Time
	CompletedAt          *time.Time
	CancelledAt          *time.Time
	UpdatedAt            time.Time
	StartCode            string
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) error {
	_, err := q.db.Exec(ctx, updateBooking,
		arg.ID,
		arg.Status,
		arg.TotalPaisa,
		arg.StartCodeAttempts,
		arg.StartCodeLockedUntil,
		arg.CashReceived,
		arg.CancelReason,
		arg.CancelledBy,
		arg.RejectReason,
		arg.AcceptedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CancelledAt,
		arg.UpdatedAt,
		arg.StartCode,
	)
	return err
}

const upsertProposal = `-- name: UpsertProposal :exec
INSERT INTO booking.extras_proposals (id, booking_id, status, added_paisa, proposed_at, decided_at) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET status = excluded.status, decided_at = excluded.decided_at
`

type UpsertProposalParams struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	Status     string
	AddedPaisa int64
	ProposedAt time.Time
	DecidedAt  *time.Time
}

func (q *Queries) UpsertProposal(ctx context.Context, arg UpsertProposalParams) error {
	_, err := q.db.Exec(ctx, upsertProposal,
		arg.ID,
		arg.BookingID,
		arg.Status,
		arg.AddedPaisa,
		arg.ProposedAt,
		arg.DecidedAt,
	)
	return err
}
