// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type AuditEntry struct {
	ID          uuid.UUID
	At          time.Time
	ActorID     *uuid.UUID
	ActorRole   string
	Action      string
	SubjectType string
	SubjectID   string
	Reason      string
	Before      []byte
	After       []byte
	EventID     *uuid.UUID
}

type AuditProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}
