// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendEntry = `-- name: AppendEntry :exec
INSERT INTO audit.entries (id, at, actor_id, actor_role, action, subject_type, subject_id, reason, before, after, event_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (event_id) DO NOTHING
`

type AppendEntryParams struct {
	ID          uuid.UUID
	At          time.Time
	ActorID     *uuid.UUID
	ActorRole   string
	Action      string
	SubjectType string
	SubjectID   string
	Reason      string
	Before      []byte
	After       []byte
	EventID     *uuid.UUID
}

func (q *Queries) AppendEntry(ctx context.Context, arg AppendEntryParams) error {
	_, err := q.db.Exec(ctx, appendEntry,
		arg.ID,
		arg.At,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.Reason,
		arg.Before,
		arg.After,
		arg.EventID,
	)
	return err
}

const list = `-- name: List :many
SELECT id, at, actor_id, actor_role, action, subject_type, subject_id, reason, before, after
FROM audit.entries
WHERE ($1::uuid IS NULL OR actor_id = $1)
  AND ($2::text IS NULL OR action = $2)
  AND ($3::text IS NULL OR subject_type = $3)
  AND ($4::text IS NULL OR subject_id = $4)
  AND ($5::timestamptz IS NULL OR at >= $5)
  AND ($6::timestamptz IS NULL OR at <= $6)
  AND ($7::timestamptz IS NULL OR (at, id) < ($7, $8::uuid))
ORDER BY at DESC, id DESC
LIMIT $9
`

type ListParams struct {
	ActorID     *uuid.UUID
	Action      *string
	SubjectType *string
	SubjectID   *string
	FromAt      *time.Time
	ToAt        *time.Time
	CursorAt    *time.Time
	CursorID    *uuid.UUID
	PageSize    int32
}

type ListRow struct {
	ID          uuid.UUID
	At          time.Time
	ActorID     *uuid.UUID
	ActorRole   string
	Action      string
	SubjectType string
	SubjectID   string
	Reason      string
	Before      []byte
	After       []byte
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]ListRow, error) {
	rows, err := q.db.Query(ctx, list,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.FromAt,
		arg.ToAt,
		arg.CursorAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRow
	for rows.Next() {
		var i ListRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.SubjectType,
			&i.SubjectID,
			&i.Reason,
			&i.Before,
			&i.After,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
