#!/usr/bin/env bash
# Generates backend/.go-arch-lint.yml from the module folders so the per-module boundary
# rules of PRD §9.3 stay explicit without hand-maintaining 60+ components. Only layers
# that exist on disk become components.
set -euo pipefail

all_modules=(identity customer provider verification catalog booking rating notification media admin audit)
layers=(contract domain port app adapter root)
root="$(cd "$(dirname "$0")/.." && pwd)"
out="${1:-$root/backend/.go-arch-lint.yml}"
modules_dir="$root/backend/internal/modules"

layer_glob() {
  case "$2" in
    domain | app | adapter) printf 'modules/%s/%s/**' "$1" "$2" ;;
    root) printf 'modules/%s' "$1" ;;
    *) printf 'modules/%s/%s' "$1" "$2" ;;
  esac
}

layer_exists() {
  if [[ "$2" == root ]]; then
    compgen -G "$modules_dir/$1/*.go" >/dev/null
  else
    [[ -d "$modules_dir/$1/$2" ]]
  fi
}

# allowed_layers lists the same-module layers a layer may import (dependencies point inwards).
allowed_layers() {
  case "$1" in
    contract) printf '' ;;
    domain) printf '' ;;
    port) printf 'domain contract' ;;
    app) printf 'domain port contract' ;;
    adapter) printf 'domain port app contract' ;;
    root) printf 'domain port app adapter contract' ;;
  esac
}

components=()
for m in "${all_modules[@]}"; do
  for l in "${layers[@]}"; do
    layer_exists "$m" "$l" && components+=("${m}_${l}")
  done
done

has() {
  local c
  for c in "${components[@]+"${components[@]}"}"; do [[ "$c" == "$1" ]] && return 0; done
  return 1
}

{
  cat <<'HEAD'
# Generated by scripts/gen-arch-lint.sh — edit the script, not this file.
# Enforces PRD §9.3: a module imports only other modules' contract packages and
# platform; domain imports only the standard library (plus the UUID type).
version: 3
workdir: internal
allow:
  depOnAnyVendor: false
# Tests may use the test kit and fixtures freely.
excludeFiles:
  - "^.*_test\\.go$"
vendors:
  uuid: { in: github.com/google/uuid }
components:
  platform: { in: platform/** }
  testkit: { in: testkit }
  app: { in: app }
HEAD
  for c in "${components[@]+"${components[@]}"}"; do
    printf '  %s: { in: %s }\n' "$c" "$(layer_glob "${c%_*}" "${c##*_}")"
  done
  printf 'commonComponents: []\ndeps:\n  platform:\n    anyVendorDeps: true\n    mayDependOn: [platform]\n'
  printf '  testkit:\n    anyVendorDeps: true\n    anyProjectDeps: true\n'
  # The composition root wires every module, so it may import anything.
  printf '  app:\n    anyVendorDeps: true\n    anyProjectDeps: true\n'
  for c in "${components[@]+"${components[@]}"}"; do
    m="${c%_*}" l="${c##*_}"
    printf '  %s:\n' "$c"
    case "$l" in
      adapter | root) printf '    anyVendorDeps: true\n' ;;
      *) printf '    canUse: [uuid]\n' ;;
    esac
    # A component may import its own sub-packages (e.g. adapter/postgres/sqlcdb).
    if [[ "$l" == domain ]]; then
      printf '    mayDependOn: [%s]\n' "$c"
      continue
    fi
    printf '    mayDependOn:\n      - platform\n      - %s\n' "$c"
    for dep in $(allowed_layers "$l"); do
      if has "${m}_${dep}"; then printf '      - %s_%s\n' "$m" "$dep"; fi
    done
    [[ "$l" == contract ]] && continue
    for other in "${all_modules[@]}"; do
      if [[ "$other" != "$m" ]] && has "${other}_contract"; then printf '      - %s_contract\n' "$other"; fi
    done
  done
} >"$out"
