#!/usr/bin/env bash
# Generates backend/.go-arch-lint.yml from the module list so the per-module boundary
# rules of PRD §9.3 stay explicit without hand-maintaining 60+ components.
set -euo pipefail

all_modules=(identity customer provider verification catalog booking rating notification media admin audit)
out="${1:-backend/.go-arch-lint.yml}"
root="$(cd "$(dirname "$0")/.." && pwd)"
modules=()
for m in "${all_modules[@]}"; do
  [[ -d "$root/backend/internal/modules/$m" ]] && modules+=("$m")
done

contracts() {
  local m
  for m in "${modules[@]+"${modules[@]}"}"; do printf '      - %s_contract\n' "$m"; done
}

{
  cat <<'HEAD'
# Generated by scripts/gen-arch-lint.sh — edit the script, not this file.
# Enforces PRD §9.3: a module imports only other modules' contract packages and
# platform; domain imports only the standard library (plus the UUID type).
version: 3
workdir: internal
allow:
  depOnAnyVendor: false
vendors:
  uuid: { in: github.com/google/uuid }
components:
  platform: { in: platform/** }
HEAD
  for m in "${modules[@]+"${modules[@]}"}"; do
    cat <<COMP
  ${m}_contract: { in: modules/${m}/contract }
  ${m}_domain: { in: modules/${m}/domain/** }
  ${m}_port: { in: modules/${m}/port }
  ${m}_app: { in: modules/${m}/app/** }
  ${m}_adapter: { in: modules/${m}/adapter/** }
  ${m}_root: { in: modules/${m} }
COMP
  done
  cat <<'DEPS'
commonComponents: []
deps:
  platform:
    anyVendorDeps: true
    mayDependOn: [platform]
DEPS
  for m in "${modules[@]+"${modules[@]}"}"; do
    cat <<DEP
  ${m}_contract:
    canUse: [uuid]
    mayDependOn: [platform]
  ${m}_domain:
    canUse: [uuid]
  ${m}_port:
    canUse: [uuid]
    mayDependOn:
      - ${m}_domain
      - platform
$(contracts)
  ${m}_app:
    canUse: [uuid]
    mayDependOn:
      - ${m}_domain
      - ${m}_port
      - platform
$(contracts)
  ${m}_adapter:
    anyVendorDeps: true
    mayDependOn:
      - ${m}_domain
      - ${m}_port
      - ${m}_app
      - platform
$(contracts)
  ${m}_root:
    anyVendorDeps: true
    mayDependOn:
      - ${m}_domain
      - ${m}_port
      - ${m}_app
      - ${m}_adapter
      - platform
$(contracts)
DEP
  done
} >"$out"
