targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: true
          # Unknown keys are ignored so older app versions keep working when the API
          # adds fields.
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          ignore_unannotated: false
          include_if_null: false
