// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type IdentityAccount struct {
	ID        uuid.UUID
	Phone     *string
	Email     *string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

type IdentityAccountRole struct {
	AccountID uuid.UUID
	Role      string
	GrantedAt time.Time
}

type IdentityAdminCredential struct {
	AccountID          uuid.UUID
	PasswordHash       string
	MustChangePassword bool
	TotpSecretEnc      []byte
	TotpEnrolled       bool
	FailedAttempts     int32
	LockedUntil        *time.Time
	Active             bool
	LastLoginAt        *time.Time
}

type IdentityBlockedPhone struct {
	Phone     string
	Reason    string
	BlockedAt time.Time
}

type IdentityOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type IdentityPermission struct {
	Name        string
	Description string
}

type IdentityProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type IdentityRole struct {
	Name        string
	Description string
	IsAdmin     bool
}

type IdentityRolePermission struct {
	Role       string
	Permission string
}

type IdentityRoleScreen struct {
	Role     string
	ScreenID string
}

type IdentityScreen struct {
	ID   string
	App  string
	Name string
}
