// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountByEmail = `-- name: AccountByEmail :one
SELECT a.id, a.phone, a.email, a.name, a.status, a.created_at, a.deleted_at,
       coalesce(array_agg(r.role ORDER BY r.role) FILTER (WHERE r.role IS NOT NULL), '{}')::text[] AS roles
FROM identity.accounts a LEFT JOIN identity.account_roles r ON r.account_id = a.id
WHERE lower(a.email) = lower($1)
GROUP BY a.id
`

type AccountByEmailRow struct {
	ID        uuid.UUID
	Phone     *string
	Email     *string
	Name      string
	Status    string
	CreatedAt time.Time
	DeletedAt *time.Time
	Roles     []string
}

func (q *Queries) AccountByEmail(ctx context.Context, lower string) (AccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, accountByEmail, lower)
	var i AccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Roles,
	)
	return i, err
}

const accountByID = `-- name: AccountByID :one
SELECT a.id, a.phone, a.email, a.name, a.status, a.created_at, a.deleted_at,
       coalesce(array_agg(r.role ORDER BY r.role) FILTER (WHERE r.role IS NOT NULL), '{}')::text[] AS roles
FROM identity.accounts a LEFT JOIN identity.account_roles r ON r.account_id = a.id
WHERE a.id = $1
GROUP BY a.id
`

type AccountByIDRow struct {
	ID        uuid.UUID
	Phone     *string
	Email     *string
	Name      string
	Status    string
	CreatedAt time.Time
	DeletedAt *time.Time
	Roles     []string
}

func (q *Queries) AccountByID(ctx context.Context, id uuid.UUID) (AccountByIDRow, error) {
	row := q.db.QueryRow(ctx, accountByID, id)
	var i AccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Roles,
	)
	return i, err
}

const accountByPhone = `-- name: AccountByPhone :one
SELECT a.id, a.phone, a.email, a.name, a.status, a.created_at, a.deleted_at,
       coalesce(array_agg(r.role ORDER BY r.role) FILTER (WHERE r.role IS NOT NULL), '{}')::text[] AS roles
FROM identity.accounts a LEFT JOIN identity.account_roles r ON r.account_id = a.id
WHERE a.phone = $1
GROUP BY a.id
`

type AccountByPhoneRow struct {
	ID        uuid.UUID
	Phone     *string
	Email     *string
	Name      string
	Status    string
	CreatedAt time.Time
	DeletedAt *time.Time
	Roles     []string
}

func (q *Queries) AccountByPhone(ctx context.Context, phone *string) (AccountByPhoneRow, error) {
	row := q.db.QueryRow(ctx, accountByPhone, phone)
	var i AccountByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Roles,
	)
	return i, err
}

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO identity.role_permissions (role, permission) VALUES ($1, $2)
`

type AddRolePermissionParams struct {
	Role       string
	Permission string
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission, arg.Role, arg.Permission)
	return err
}

const addRoleScreen = `-- name: AddRoleScreen :exec
INSERT INTO identity.role_screens (role, screen_id) VALUES ($1, $2)
`

type AddRoleScreenParams struct {
	Role     string
	ScreenID string
}

func (q *Queries) AddRoleScreen(ctx context.Context, arg AddRoleScreenParams) error {
	_, err := q.db.Exec(ctx, addRoleScreen, arg.Role, arg.ScreenID)
	return err
}

const adminCredentials = `-- name: AdminCredentials :one
SELECT account_id, password_hash, must_change_password, totp_secret_enc, totp_enrolled,
       failed_attempts, locked_until, active, last_login_at
FROM identity.admin_credentials WHERE account_id = $1
`

func (q *Queries) AdminCredentials(ctx context.Context, accountID uuid.UUID) (IdentityAdminCredential, error) {
	row := q.db.QueryRow(ctx, adminCredentials, accountID)
	var i IdentityAdminCredential
	err := row.Scan(
		&i.AccountID,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.TotpSecretEnc,
		&i.TotpEnrolled,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.Active,
		&i.LastLoginAt,
	)
	return i, err
}

const allPermissions = `-- name: AllPermissions :many
SELECT name FROM identity.permissions ORDER BY name
`

func (q *Queries) AllPermissions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, allPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allScreens = `-- name: AllScreens :many
SELECT id FROM identity.screens ORDER BY id
`

func (q *Queries) AllScreens(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, allScreens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const anonymiseAccount = `-- name: AnonymiseAccount :exec
UPDATE identity.accounts SET phone = NULL, email = NULL, name = '', deleted_at = $2, updated_at = $2 WHERE id = $1
`

type AnonymiseAccountParams struct {
	ID        uuid.UUID
	DeletedAt *time.Time
}

func (q *Queries) AnonymiseAccount(ctx context.Context, arg AnonymiseAccountParams) error {
	_, err := q.db.Exec(ctx, anonymiseAccount, arg.ID, arg.DeletedAt)
	return err
}

const blockPhone = `-- name: BlockPhone :exec
INSERT INTO identity.blocked_phones (phone, reason, blocked_at) VALUES ($1, $2, $3)
ON CONFLICT (phone) DO NOTHING
`

type BlockPhoneParams struct {
	Phone     string
	Reason    string
	BlockedAt time.Time
}

func (q *Queries) BlockPhone(ctx context.Context, arg BlockPhoneParams) error {
	_, err := q.db.Exec(ctx, blockPhone, arg.Phone, arg.Reason, arg.BlockedAt)
	return err
}

const clearRole = `-- name: ClearRole :exec
WITH p AS (DELETE FROM identity.role_permissions WHERE role_permissions.role = $1)
DELETE FROM identity.role_screens WHERE role_screens.role = $1
`

func (q *Queries) ClearRole(ctx context.Context, role string) error {
	_, err := q.db.Exec(ctx, clearRole, role)
	return err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO identity.accounts (id, phone, email, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
`

type CreateAccountParams struct {
	ID        uuid.UUID
	Phone     *string
	Email     *string
	Name      string
	Status    string
	CreatedAt time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.Phone,
		arg.Email,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const createAdminCredentials = `-- name: CreateAdminCredentials :exec
INSERT INTO identity.admin_credentials (account_id, password_hash, must_change_password)
VALUES ($1, $2, true)
`

type CreateAdminCredentialsParams struct {
	AccountID    uuid.UUID
	PasswordHash string
}

func (q *Queries) CreateAdminCredentials(ctx context.Context, arg CreateAdminCredentialsParams) error {
	_, err := q.db.Exec(ctx, createAdminCredentials, arg.AccountID, arg.PasswordHash)
	return err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO identity.account_roles (account_id, role, granted_at) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type GrantRoleParams struct {
	AccountID uuid.UUID
	Role      string
	GrantedAt time.Time
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.Exec(ctx, grantRole, arg.AccountID, arg.Role, arg.GrantedAt)
	return err
}

const isPhoneBlocked = `-- name: IsPhoneBlocked :one
SELECT EXISTS (SELECT 1 FROM identity.blocked_phones WHERE phone = $1)
`

func (q *Queries) IsPhoneBlocked(ctx context.Context, phone string) (bool, error) {
	row := q.db.QueryRow(ctx, isPhoneBlocked, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT a.id, a.phone, a.email, a.name, a.status, a.created_at, a.deleted_at,
       coalesce(array_agg(r.role ORDER BY r.role) FILTER (WHERE r.role IS NOT NULL), '{}')::text[] AS roles,
       c.password_hash, c.must_change_password, c.totp_secret_enc, c.totp_enrolled,
       c.failed_attempts, c.locked_until, c.active, c.last_login_at
FROM identity.admin_credentials c
JOIN identity.accounts a ON a.id = c.account_id
LEFT JOIN identity.account_roles r ON r.account_id = a.id
WHERE a.deleted_at IS NULL
GROUP BY a.id, c.account_id
ORDER BY a.email
`

type ListAdminsRow struct {
	ID                 uuid.UUID
	Phone              *string
	Email              *string
	Name               string
	Status             string
	CreatedAt          time.Time
	DeletedAt          *time.Time
	Roles              []string
	PasswordHash       string
	MustChangePassword bool
	TotpSecretEnc      []byte
	TotpEnrolled       bool
	FailedAttempts     int32
	LockedUntil        *time.Time
	Active             bool
	LastLoginAt        *time.Time
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsRow
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.Roles,
			&i.PasswordHash,
			&i.MustChangePassword,
			&i.TotpSecretEnc,
			&i.TotpEnrolled,
			&i.FailedAttempts,
			&i.LockedUntil,
			&i.Active,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT name FROM identity.roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRoles = `-- name: RevokeRoles :exec
DELETE FROM identity.account_roles WHERE account_id = $1
`

func (q *Queries) RevokeRoles(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRoles, accountID)
	return err
}

const rolePermissions = `-- name: RolePermissions :many
SELECT permission FROM identity.role_permissions WHERE role = $1 ORDER BY permission
`

func (q *Queries) RolePermissions(ctx context.Context, role string) ([]string, error) {
	rows, err := q.db.Query(ctx, rolePermissions, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const roleScreens = `-- name: RoleScreens :many
SELECT screen_id FROM identity.role_screens WHERE role = $1 ORDER BY screen_id
`

func (q *Queries) RoleScreens(ctx context.Context, role string) ([]string, error) {
	rows, err := q.db.Query(ctx, roleScreens, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var screen_id string
		if err := rows.Scan(&screen_id); err != nil {
			return nil, err
		}
		items = append(items, screen_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockPhone = `-- name: UnblockPhone :exec
DELETE FROM identity.blocked_phones WHERE phone = $1
`

func (q *Queries) UnblockPhone(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, unblockPhone, phone)
	return err
}

const updateAdminCredentials = `-- name: UpdateAdminCredentials :exec
UPDATE identity.admin_credentials
SET password_hash = $2, must_change_password = $3, totp_secret_enc = $4, totp_enrolled = $5,
    failed_attempts = $6, locked_until = $7, active = $8, last_login_at = $9
WHERE account_id = $1
`

type UpdateAdminCredentialsParams struct {
	AccountID          uuid.UUID
	PasswordHash       string
	MustChangePassword bool
	TotpSecretEnc      []byte
	TotpEnrolled       bool
	FailedAttempts     int32
	LockedUntil        *time.Time
	Active             bool
	LastLoginAt        *time.Time
}

func (q *Queries) UpdateAdminCredentials(ctx context.Context, arg UpdateAdminCredentialsParams) error {
	_, err := q.db.Exec(ctx, updateAdminCredentials,
		arg.AccountID,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.TotpSecretEnc,
		arg.TotpEnrolled,
		arg.FailedAttempts,
		arg.LockedUntil,
		arg.Active,
		arg.LastLoginAt,
	)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE identity.accounts SET status = $2, updated_at = $3 WHERE id = $1
`

type UpdateStatusParams struct {
	ID        uuid.UUID
	Status    string
	UpdatedAt time.Time
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.Exec(ctx, updateStatus, arg.ID, arg.Status, arg.UpdatedAt)
	return err
}
