// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type ProviderCancellation struct {
	BookingID  uuid.UUID
	ProviderID uuid.UUID
	At         time.Time
}

type ProviderOutbox struct {
	ID            uuid.UUID
	AggregateID   string
	EventName     string
	Payload       []byte
	CreatedAt     time.Time
	PublishedAt   *time.Time
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	Dead          bool
}

type ProviderProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type ProviderProvider struct {
	ID                  uuid.UUID
	Phone               string
	FullName            string
	DateOfBirth         *time.Time
	Gender              *string
	PresentAddress      string
	PermanentAddress    string
	Bio                 string
	PhotoMediaID        *uuid.UUID
	ExperienceYears     int32
	Language            string
	HomeBase            interface{}
	WorkingRadiusM      int32
	EmergencyName       string
	EmergencyRelation   string
	EmergencyPhone      string
	EmergencyVerifiedAt *time.Time
	CocVersion          string
	CocAcceptedAt       *time.Time
	StepsDone           []string
	SubmittedAt         *time.Time
	AccountStatus       string
	Level               int32
	CanReceiveBookings  bool
	RatingAvg           float64
	RatingCount         int32
	CompletedJobs       int32
	FlaggedForReview    bool
	FlagReason          string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ProviderProviderService struct {
	ProviderID uuid.UUID
	ServiceID  uuid.UUID
}
