// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCancellation = `-- name: AddCancellation :exec
INSERT INTO provider.cancellations (booking_id, provider_id, at) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddCancellationParams struct {
	BookingID  uuid.UUID
	ProviderID uuid.UUID
	At         time.Time
}

func (q *Queries) AddCancellation(ctx context.Context, arg AddCancellationParams) error {
	_, err := q.db.Exec(ctx, addCancellation, arg.BookingID, arg.ProviderID, arg.At)
	return err
}

const addCompletedJob = `-- name: AddCompletedJob :exec
UPDATE provider.providers SET completed_jobs = completed_jobs + 1 WHERE id = $1
`

func (q *Queries) AddCompletedJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, addCompletedJob, id)
	return err
}

const addService = `-- name: AddService :exec
INSERT INTO provider.provider_services (provider_id, service_id) VALUES ($1, $2)
`

type AddServiceParams struct {
	ProviderID uuid.UUID
	ServiceID  uuid.UUID
}

func (q *Queries) AddService(ctx context.Context, arg AddServiceParams) error {
	_, err := q.db.Exec(ctx, addService, arg.ProviderID, arg.ServiceID)
	return err
}

const candidates = `-- name: Candidates :many
SELECT id, full_name, photo_media_id, gender, level, rating_avg, rating_count, completed_jobs, working_radius_m
FROM provider.providers WHERE id = ANY($1::uuid[]) AND account_status = 'active' AND level >= $2
`

type CandidatesParams struct {
	Ids      []uuid.UUID
	MinLevel int32
}

type CandidatesRow struct {
	ID             uuid.UUID
	FullName       string
	PhotoMediaID   *uuid.UUID
	Gender         *string
	Level          int32
	RatingAvg      float64
	RatingCount    int32
	CompletedJobs  int32
	WorkingRadiusM int32
}

func (q *Queries) Candidates(ctx context.Context, arg CandidatesParams) ([]CandidatesRow, error) {
	rows, err := q.db.Query(ctx, candidates, arg.Ids, arg.MinLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandidatesRow
	for rows.Next() {
		var i CandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.PhotoMediaID,
			&i.Gender,
			&i.Level,
			&i.RatingAvg,
			&i.RatingCount,
			&i.CompletedJobs,
			&i.WorkingRadiusM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearServices = `-- name: ClearServices :exec
DELETE FROM provider.provider_services WHERE provider_id = $1
`

func (q *Queries) ClearServices(ctx context.Context, providerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearServices, providerID)
	return err
}

const countCancellations = `-- name: CountCancellations :one
SELECT count(*) FROM provider.cancellations WHERE provider_id = $1 AND at > $2
`

type CountCancellationsParams struct {
	ProviderID uuid.UUID
	At         time.Time
}

func (q *Queries) CountCancellations(ctx context.Context, arg CountCancellationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCancellations, arg.ProviderID, arg.At)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM provider.providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const ensureProvider = `-- name: EnsureProvider :exec
INSERT INTO provider.providers (id, phone, created_at, updated_at) VALUES ($1, $2, $3, $3)
ON CONFLICT (id) DO NOTHING
`

type EnsureProviderParams struct {
	ID        uuid.UUID
	Phone     string
	CreatedAt time.Time
}

func (q *Queries) EnsureProvider(ctx context.Context, arg EnsureProviderParams) error {
	_, err := q.db.Exec(ctx, ensureProvider, arg.ID, arg.Phone, arg.CreatedAt)
	return err
}

const flag = `-- name: Flag :execrows
UPDATE provider.providers SET flagged_for_review = true, flag_reason = $2 WHERE id = $1 AND NOT flagged_for_review
`

type FlagParams struct {
	ID         uuid.UUID
	FlagReason string
}

func (q *Queries) Flag(ctx context.Context, arg FlagParams) (int64, error) {
	result, err := q.db.Exec(ctx, flag, arg.ID, arg.FlagReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const providerByID = `-- name: ProviderByID :one
SELECT id, phone, full_name, date_of_birth, gender, present_address, permanent_address, bio, photo_media_id,
    experience_years, language, COALESCE(ST_Y(home_base::geometry), 0)::float8 AS home_lat, COALESCE(ST_X(home_base::geometry), 0)::float8 AS home_lng,
    (home_base IS NOT NULL)::bool AS has_home_base, working_radius_m, emergency_name, emergency_relation, emergency_phone,
    emergency_verified_at, coc_version, coc_accepted_at, steps_done, submitted_at, account_status, level,
    rating_avg, rating_count, completed_jobs, flagged_for_review, flag_reason, created_at,
    COALESCE((SELECT array_agg(s.service_id ORDER BY s.service_id) FROM provider.provider_services s WHERE s.provider_id = p.id), '{}')::uuid[] AS service_ids
FROM provider.providers p WHERE id = $1
`

type ProviderByIDRow struct {
	ID                  uuid.UUID
	Phone               string
	FullName            string
	DateOfBirth         *time.Time
	Gender              *string
	PresentAddress      string
	PermanentAddress    string
	Bio                 string
	PhotoMediaID        *uuid.UUID
	ExperienceYears     int32
	Language            string
	HomeLat             float64
	HomeLng             float64
	HasHomeBase         bool
	WorkingRadiusM      int32
	EmergencyName       string
	EmergencyRelation   string
	EmergencyPhone      string
	EmergencyVerifiedAt *time.Time
	CocVersion          string
	CocAcceptedAt       *time.Time
	StepsDone           []string
	SubmittedAt         *time.Time
	AccountStatus       string
	Level               int32
	RatingAvg           float64
	RatingCount         int32
	CompletedJobs       int32
	FlaggedForReview    bool
	FlagReason          string
	CreatedAt           time.Time
	ServiceIds          []uuid.UUID
}

func (q *Queries) ProviderByID(ctx context.Context, id uuid.UUID) (ProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, providerByID, id)
	var i ProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.PresentAddress,
		&i.PermanentAddress,
		&i.Bio,
		&i.PhotoMediaID,
		&i.ExperienceYears,
		&i.Language,
		&i.HomeLat,
		&i.HomeLng,
		&i.HasHomeBase,
		&i.WorkingRadiusM,
		&i.EmergencyName,
		&i.EmergencyRelation,
		&i.EmergencyPhone,
		&i.EmergencyVerifiedAt,
		&i.CocVersion,
		&i.CocAcceptedAt,
		&i.StepsDone,
		&i.SubmittedAt,
		&i.AccountStatus,
		&i.Level,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CompletedJobs,
		&i.FlaggedForReview,
		&i.FlagReason,
		&i.CreatedAt,
		&i.ServiceIds,
	)
	return i, err
}

const saveProfile = `-- name: SaveProfile :exec
UPDATE provider.providers SET full_name = $1, date_of_birth = $2, gender = $3,
    present_address = $4, permanent_address = $5, bio = $6,
    photo_media_id = $7, experience_years = $8, language = $9,
    home_base = CASE WHEN $10::bool
        THEN ST_SetSRID(ST_MakePoint($11::float8, $12::float8), 4326)::geography END,
    working_radius_m = $13, emergency_name = $14,
    emergency_relation = $15, emergency_phone = $16,
    emergency_verified_at = $17, coc_version = $18,
    coc_accepted_at = $19, steps_done = $20, submitted_at = $21,
    updated_at = $22
WHERE id = $23
`

type SaveProfileParams struct {
	FullName            string
	DateOfBirth         *time.Time
	Gender              *string
	PresentAddress      string
	PermanentAddress    string
	Bio                 string
	PhotoMediaID        *uuid.UUID
	ExperienceYears     int32
	Language            string
	HasHomeBase         bool
	HomeLng             float64
	HomeLat             float64
	WorkingRadiusM      int32
	EmergencyName       string
	EmergencyRelation   string
	EmergencyPhone      string
	EmergencyVerifiedAt *time.Time
	CocVersion          string
	CocAcceptedAt       *time.Time
	StepsDone           []string
	SubmittedAt         *time.Time
	UpdatedAt           time.Time
	ID                  uuid.UUID
}

func (q *Queries) SaveProfile(ctx context.Context, arg SaveProfileParams) error {
	_, err := q.db.Exec(ctx, saveProfile,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.PresentAddress,
		arg.PermanentAddress,
		arg.Bio,
		arg.PhotoMediaID,
		arg.ExperienceYears,
		arg.Language,
		arg.HasHomeBase,
		arg.HomeLng,
		arg.HomeLat,
		arg.WorkingRadiusM,
		arg.EmergencyName,
		arg.EmergencyRelation,
		arg.EmergencyPhone,
		arg.EmergencyVerifiedAt,
		arg.CocVersion,
		arg.CocAcceptedAt,
		arg.StepsDone,
		arg.SubmittedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const searchProviders = `-- name: SearchProviders :many
SELECT p.id, p.full_name, p.phone,
    (CASE WHEN p.account_status = 'active' AND p.level = 0 THEN 'pending' ELSE p.account_status END)::text AS status,
    p.level, p.rating_avg, p.rating_count, p.completed_jobs, p.flagged_for_review, p.flag_reason, p.created_at,
    COALESCE(array_agg(s.service_id ORDER BY s.service_id) FILTER (WHERE s.service_id IS NOT NULL), '{}')::uuid[] AS service_ids
FROM provider.providers p
LEFT JOIN provider.provider_services s ON s.provider_id = p.id
WHERE ($1::uuid IS NULL OR p.id = $1::uuid)
  AND ($2::text = '' OR lower(p.full_name) LIKE $2::text OR p.phone LIKE $2::text)
  AND ($3::text IS NULL
       OR (CASE WHEN p.account_status = 'active' AND p.level = 0 THEN 'pending' ELSE p.account_status END) = $3::text)
  AND ($4::int IS NULL OR p.level = $4::int)
  AND ($5::bool IS NULL OR p.flagged_for_review = $5::bool)
  AND ($6::timestamptz IS NULL OR (p.created_at, p.id) < ($6::timestamptz, $7::uuid))
GROUP BY p.id
ORDER BY p.created_at DESC, p.id DESC
LIMIT $8
`

type SearchProvidersParams struct {
	ID       *uuid.UUID
	Pattern  string
	Status   *string
	Level    *int32
	Flagged  *bool
	BeforeAt *time.Time
	BeforeID uuid.UUID
	MaxRows  int32
}

type SearchProvidersRow struct {
	ID               uuid.UUID
	FullName         string
	Phone            string
	Status           string
	Level            int32
	RatingAvg        float64
	RatingCount      int32
	CompletedJobs    int32
	FlaggedForReview bool
	FlagReason       string
	CreatedAt        time.Time
	ServiceIds       []uuid.UUID
}

// An active provider without Level 1 is listed as pending verification (PRD §6.4).
func (q *Queries) SearchProviders(ctx context.Context, arg SearchProvidersParams) ([]SearchProvidersRow, error) {
	rows, err := q.db.Query(ctx, searchProviders,
		arg.ID,
		arg.Pattern,
		arg.Status,
		arg.Level,
		arg.Flagged,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProvidersRow
	for rows.Next() {
		var i SearchProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Status,
			&i.Level,
			&i.RatingAvg,
			&i.RatingCount,
			&i.CompletedJobs,
			&i.FlaggedForReview,
			&i.FlagReason,
			&i.CreatedAt,
			&i.ServiceIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAccountStatus = `-- name: SetAccountStatus :exec
UPDATE provider.providers SET account_status = $2 WHERE id = $1
`

type SetAccountStatusParams struct {
	ID            uuid.UUID
	AccountStatus string
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountStatus, arg.ID, arg.AccountStatus)
	return err
}

const setLevel = `-- name: SetLevel :exec
UPDATE provider.providers SET level = $2 WHERE id = $1
`

type SetLevelParams struct {
	ID    uuid.UUID
	Level int32
}

func (q *Queries) SetLevel(ctx context.Context, arg SetLevelParams) error {
	_, err := q.db.Exec(ctx, setLevel, arg.ID, arg.Level)
	return err
}

const setRating = `-- name: SetRating :one
UPDATE provider.providers SET rating_avg = $2, rating_count = $3 WHERE id = $1 RETURNING completed_jobs
`

type SetRatingParams struct {
	ID          uuid.UUID
	RatingAvg   float64
	RatingCount int32
}

func (q *Queries) SetRating(ctx context.Context, arg SetRatingParams) (int32, error) {
	row := q.db.QueryRow(ctx, setRating, arg.ID, arg.RatingAvg, arg.RatingCount)
	var completed_jobs int32
	err := row.Scan(&completed_jobs)
	return completed_jobs, err
}
