// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"time"

	"github.com/google/uuid"
)

type NotificationDeviceToken struct {
	Token     string
	AccountID uuid.UUID
	App       string
	Platform  string
	UpdatedAt time.Time
}

type NotificationNotification struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
	App         string
	Type        string
	Title       string
	Body        string
	BookingID   *uuid.UUID
	DedupeKey   string
	ReadAt      *time.Time
	CreatedAt   time.Time
}

type NotificationProcessedEvent struct {
	Handler     string
	EventID     uuid.UUID
	ProcessedAt time.Time
}

type NotificationRecipient struct {
	AccountID uuid.UUID
	Language  string
}
