// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnread = `-- name: CountUnread :one
SELECT count(*) FROM notification.notifications WHERE recipient_id = $1 AND app = $2 AND read_at IS NULL
`

type CountUnreadParams struct {
	RecipientID uuid.UUID
	App         string
}

func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, arg.RecipientID, arg.App)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountNotifications = `-- name: DeleteAccountNotifications :exec
DELETE FROM notification.notifications WHERE recipient_id = $1
`

func (q *Queries) DeleteAccountNotifications(ctx context.Context, recipientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountNotifications, recipientID)
	return err
}

const deleteAccountTokens = `-- name: DeleteAccountTokens :exec
DELETE FROM notification.device_tokens WHERE account_id = $1
`

func (q *Queries) DeleteAccountTokens(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountTokens, accountID)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM notification.device_tokens WHERE token = $1
`

func (q *Queries) DeleteToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteToken, token)
	return err
}

const insertNotification = `-- name: InsertNotification :execrows
INSERT INTO notification.notifications (id, recipient_id, app, type, title, body, booking_id, dedupe_key, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT (recipient_id, dedupe_key) DO NOTHING
`

type InsertNotificationParams struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
	App         string
	Type        string
	Title       string
	Body        string
	BookingID   *uuid.UUID
	DedupeKey   string
	CreatedAt   time.Time
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.RecipientID,
		arg.App,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.BookingID,
		arg.DedupeKey,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, type, title, body, booking_id, read_at, created_at FROM notification.notifications
WHERE recipient_id = $1 AND app = $2
  AND ($3::timestamptz IS NULL OR (created_at, id) < ($3, $4::uuid))
ORDER BY created_at DESC, id DESC LIMIT $5
`

type ListNotificationsParams struct {
	RecipientID uuid.UUID
	App         string
	BeforeAt    *time.Time
	BeforeID    uuid.UUID
	MaxRows     int32
}

type ListNotificationsRow struct {
	ID        uuid.UUID
	Type      string
	Title     string
	Body      string
	BookingID *uuid.UUID
	ReadAt    *time.Time
	CreatedAt time.Time
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.RecipientID,
		arg.App,
		arg.BeforeAt,
		arg.BeforeID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.BookingID,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllRead = `-- name: MarkAllRead :exec
UPDATE notification.notifications SET read_at = $3 WHERE recipient_id = $1 AND app = $2 AND read_at IS NULL
`

type MarkAllReadParams struct {
	RecipientID uuid.UUID
	App         string
	ReadAt      *time.Time
}

func (q *Queries) MarkAllRead(ctx context.Context, arg MarkAllReadParams) error {
	_, err := q.db.Exec(ctx, markAllRead, arg.RecipientID, arg.App, arg.ReadAt)
	return err
}

const markRead = `-- name: MarkRead :execrows
UPDATE notification.notifications SET read_at = COALESCE(read_at, $3) WHERE id = $1 AND recipient_id = $2 AND app = $4
`

type MarkReadParams struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
	ReadAt      *time.Time
	App         string
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead,
		arg.ID,
		arg.RecipientID,
		arg.ReadAt,
		arg.App,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tokensFor = `-- name: TokensFor :many
SELECT token FROM notification.device_tokens WHERE account_id = $1 AND app = $2 ORDER BY updated_at DESC LIMIT 10
`

type TokensForParams struct {
	AccountID uuid.UUID
	App       string
}

func (q *Queries) TokensFor(ctx context.Context, arg TokensForParams) ([]string, error) {
	rows, err := q.db.Query(ctx, tokensFor, arg.AccountID, arg.App)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertToken = `-- name: UpsertToken :exec
INSERT INTO notification.device_tokens (token, account_id, app, platform, updated_at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (token) DO UPDATE SET account_id = excluded.account_id, app = excluded.app, platform = excluded.platform,
    updated_at = excluded.updated_at
`

type UpsertTokenParams struct {
	Token     string
	AccountID uuid.UUID
	App       string
	Platform  string
	UpdatedAt time.Time
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) error {
	_, err := q.db.Exec(ctx, upsertToken,
		arg.Token,
		arg.AccountID,
		arg.App,
		arg.Platform,
		arg.UpdatedAt,
	)
	return err
}
